import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import { hashValue } from '../scripts/content/campaign-sources.mjs';
import { THEORY_UI_SAMPLING_PROFILE as profile, THEORY_UI_DEPENDENCIES, theoryExampleLayout, verifyTheoryUISampling } from '../scripts/content/campaign-ui-sampling.mjs';
function fixture(t){
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'theory-ui-sampling-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));
 const write=(p,v)=>{fs.mkdirSync(path.dirname(path.join(root,p)),{recursive:true});fs.writeFileSync(path.join(root,p),typeof v==='string'?v:JSON.stringify(v));return{path:p,hash:hashValue(fs.readFileSync(path.join(root,p)))}};
 const ref=p=>({path:p,hash:hashValue(fs.readFileSync(path.join(root,p)))});
 const files=THEORY_UI_DEPENDENCIES.map(p=>write(p,'fixture:'+p));
 const assets=['src/main.js','src/lib/math-writing-box.js','public/libs/maths-editor/equation-spacing.mjs','node_modules/katex/dist/katex.mjs','node_modules/katex/dist/katex.min.css','node_modules/katex/dist/fonts/main.woff2'].map(p=>write(p,'fixture:'+p));
 const systemFonts=['segoeui.ttf','segoeuib.ttf','segoeuii.ttf','segoeuiz.ttf'].map(p=>{let r=write('system/'+p,p);return{path:path.join(root,r.path),hash:r.hash}}),binary=write('system/chrome','browser');
 const pair={content:{theory:{workedExamples:[{question_text:'Evaluate $2x$.',solution_text:'$2(3)=6$'},{question_text:'Evaluate $4x$.',solution_text:'$4(3)=12$'}]}},quiz:null};write('work/candidate.json',pair);
 const state={skillId:'child',status:'accepted',stage:{hash:'stage',candidateHash:hashValue(pair),candidatePath:'work/candidate.json',workerLineage:{actorId:'/root/author'}},review:{stageHash:'stage',pending:[],workerLineage:{actorId:'/root/reviewer',kind:'native',origin:'coordinator-bound'}}};
 write('booklets/provenance/content-campaign/worked-examples-2026-09/campaign.json',{skillIds:['child']});const statePath='booklets/provenance/content-campaign/worked-examples-2026-09/skills/child.json';write(statePath,state);
 const mechanism={profile,container:'.theory .worked-example',browserVersion:'test-browser',browserBinding:{browserVersion:'test-browser',executablePath:path.join(root,binary.path),executableHash:binary.hash},viewports:[{name:'desktop',width:1280,height:900},{name:'mobile',width:390,height:844}],appFiles:files,assets,systemFonts,producerFiles:[write('scripts/content/campaign-ui-capture.mjs','fixture driver'),write('scripts/content/campaign-ui-sampling.mjs','fixture verifier')]};
 const capture={profile,skillId:'child',stageHash:'stage',candidateHash:state.stage.candidateHash,appFiles:files,appFilesBefore:files,appFilesAfter:files,mechanism:write('work/mechanism.json',mechanism),rows:['desktop','mobile'].flatMap(name=>pair.content.theory.workedExamples.map((e,index)=>({name,index,viewport:{name,width:name==='desktop'?1280:390,height:name==='desktop'?900:844},itemHash:hashValue(e),layoutHash:theoryExampleLayout(e),container:'.theory .worked-example',actualRender:true,questionVisible:true,solutionVisible:true,workingEmpty:false,fontsReady:true,katexErrors:0,diagramCount:0,overflow:false,mathOutsideExample:0,width:300,height:index?50:100,mathWidth:100}))),artifacts:['desktop','mobile'].map(name=>({name,index:0,bounds:{width:300,height:100},...write('work/'+name+'.png','synthetic-test-pixels:'+name)}))};
 const proof={profile,accepted:true,actualRepresentativeInspection:true,applicabilityObservation:'Synthetic verifier fixture only, no content/pixel credit.',reviewerIdentity:'/root/reviewer',reviewerProfile:{workerLineage:{actorId:'/root/reviewer'},model:'gpt-6.1-sol',effort:'medium',requestedServiceTier:'default'},captures:[write('work/capture.json',capture)],artifacts:capture.artifacts.map(a=>({...a,skillId:'child',accepted:true,actualPixelInspection:true,observation:'Synthetic verifier test assertion, no actual content acceptance.'}))};
 const seal=()=>{state.review.reviewerProfile=proof.reviewerProfile;proof.inspectionLineage={skillId:'child',stageHash:'stage',profile:write('work/profile.json',proof.reviewerProfile)};write(statePath,state);capture.mechanism=write('work/mechanism.json',mechanism);proof.captures=[write('work/capture.json',capture)];return write('work/proof.json',proof)};
 return{root,write,ref,pair,state,mechanism,capture,proof,seal,verify:()=>verifyTheoryUISampling(root,seal(),{skillId:'child'})};
}
test('explicit figure-free contract checks every example while preserving honest representative pixel count',t=>{let f=fixture(t),r=f.verify();assert.equal(r.automaticallyCheckedExamples,4);assert.equal(r.actuallyInspectedArtifacts,2);assert.equal(f.capture.rows[1].actualPixelInspection,undefined);});
for(const [name,mutate] of [
 ['no opt-in',f=>delete f.proof.profile],['no applicability',f=>f.proof.applicabilityObservation=''],['self review',f=>f.state.stage.workerLineage.actorId='/root/reviewer'],['stale stage',f=>f.capture.stageHash='old'],['stale candidate',f=>f.capture.candidateHash='old'],['owned stage',f=>f.state.owner={role:'author'}],['unaccepted mathematics',f=>f.state.status='staged'],['pending review',f=>f.state.review.pending=['repair']],['old content review',f=>f.state.review.stageHash='old'],['missing row',f=>f.capture.rows.pop()],['duplicate row',f=>f.capture.rows[1]={...f.capture.rows[0]}],['foreign example',f=>f.capture.rows[0].index=22],['stale item',f=>f.capture.rows[0].itemHash='old'],['unknown container',f=>f.capture.rows[0].container='.practice'],['missing working',f=>f.capture.rows[0].workingEmpty=true],['hidden solution',f=>f.capture.rows[0].solutionVisible=false],['overflow',f=>f.capture.rows[0].overflow=true],['math clipping',f=>f.capture.rows[0].mathOutsideExample=1],['math error',f=>f.capture.rows[0].katexErrors=1],['diagram',f=>f.capture.rows[0].diagramCount=1],['fonts pending',f=>f.capture.rows[0].fontsReady=false],['missing dependency',f=>f.capture.appFiles=f.capture.appFiles.slice(1)],['duplicate dependency',f=>f.capture.appFiles=[...f.capture.appFiles.slice(1),f.capture.appFiles[1]]],['snapshot drift',f=>f.capture.appFilesAfter=[]],['browser drift',f=>f.write('system/chrome','changed')],['font drift',f=>f.write('node_modules/katex/dist/fonts/main.woff2','changed')],['system font drift',f=>f.write('system/segoeui.ttf','changed')],['producer drift',f=>f.write('scripts/content/campaign-ui-sampling.mjs','changed')],['foreign producer',f=>f.mechanism.producerFiles=[f.mechanism.producerFiles[0]]],['row viewport',f=>f.capture.rows[0].viewport.width=300],['representative geometry',f=>f.capture.artifacts[0].bounds.height=300],['wrong effort',f=>f.proof.reviewerProfile.effort='high'],['wrong tier',f=>f.proof.reviewerProfile.requestedServiceTier='fast'],['missing browser',f=>delete f.mechanism.browserBinding],['different viewport',f=>f.mechanism.viewports[1].width=320],['missing representative',f=>{f.capture.artifacts.pop();f.proof.artifacts.pop()}],['uninspected representative',f=>f.proof.artifacts[0].actualPixelInspection=false],['wrong PNG membership',f=>f.proof.artifacts[0].hash='wrong'],['duplicate PNG',f=>{f.capture.artifacts[1]={...f.capture.artifacts[0]};f.proof.artifacts[1]={...f.proof.artifacts[0]}}],['missing tallest',f=>f.capture.rows[1].height=500],['missing widest',f=>f.capture.rows[1].mathWidth=200],['different display family',f=>{f.pair.content.theory.workedExamples[1].solution_text='$$x$$';f.state.stage.candidateHash=hashValue(f.pair);f.capture.candidateHash=f.state.stage.candidateHash;f.write('work/candidate.json',f.pair);for(let r of f.capture.rows.filter(r=>r.index===1)){r.itemHash=hashValue(f.pair.content.theory.workedExamples[1]);r.layoutHash=theoryExampleLayout(f.pair.content.theory.workedExamples[1])}}]
])test('rejects '+name,t=>{let f=fixture(t);mutate(f);assert.throws(()=>f.verify(),/Theory UI sampling/)});
test('literal proof/capture tampering and foreign requested skill reject',t=>{let f=fixture(t),r=f.seal();f.write(r.path,'{}');assert.throws(()=>verifyTheoryUISampling(f.root,r),/bytes changed/);r=f.seal();assert.throws(()=>verifyTheoryUISampling(f.root,r,{skillId:'foreign'}),/outside cohort/);f.write('work/capture.json','{}');assert.throws(()=>verifyTheoryUISampling(f.root,r),/bytes changed/)});
for(const e of [{question_text:'[tikz]figure[/tikz]',solution_text:'1'},{question_text:'![image](a)',solution_text:'1'},{question_text:'<table>',solution_text:'1'},{question_text:'x',solution_text:'$\\begin{array}x\\end{array}$'},{question_text:'x',solution_text:'1',layout:{width:4}}])test('different native/structured content never enters plain family '+JSON.stringify(e),()=>assert.throws(()=>theoryExampleLayout(e),/Theory UI sampling/));

test('plain math inequality remains eligible, unlike HTML',()=>assert.ok(theoryExampleLayout({question_text:'Compare $20<55$.',solution_text:'$20<55$ is true.'})));

test('canonical candidate excludes nonpainting expected-baseline metadata',t=>{const f=fixture(t);f.write('work/candidate.json',{...f.pair,expected:{contentHash:'baseline'}});assert.equal(f.verify().automaticallyCheckedExamples,4);});
