import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import os from'node:os';import path from'node:path';import{createSourceSelectionContext,selectSourceEvidence}from'../scripts/content/campaign-source-selection.mjs';import{hashValue}from'../scripts/content/campaign-sources.mjs';
function fixture(t,{title='Represent probabilities as fractions',blurb='Express equally likely outcomes as a fraction.',id='test-skill',stage=3}={}){const root=fs.mkdtempSync(path.join(os.tmpdir(),'mathsmap-subject-selector-proposal-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const write=(p,v)=>{fs.mkdirSync(path.dirname(path.join(root,p)),{recursive:true});fs.writeFileSync(path.join(root,p),typeof v==='string'?v:JSON.stringify(v));};const skill={id,title,blurb,stage,prereqs:[],dotPointIds:['dp']};for(const[name,v]of Object.entries({skills:[skill],topics:[{id:'topic',stage,courses:['course'],title}],courses:[{id:'course',stage,order:1}],dotpoints:[{id:'dp',topicId:'topic',text:blurb,order:1}]}))write('data/'+name+'.json',v);return{root,write,skill,select:(options={})=>selectSourceEvidence({root,skillId:id,state:{scope:{stage,topicId:'topic',dotPointId:'dp'}},evidenceDir:'.agywork/no-curation',...options})};}
const formula='P(event) = \\frac{number of favourable outcomes}{total number of outcomes}';
for(const[format,working]of[['native-fraction',formula],['plain-division','Divide the number of favourable outcomes by the total number of outcomes.'],['plain-ratio','Write the number of favourable outcomes over the total number of outcomes.']])test('probability subject plus '+format+' counting outranks fraction division',t=>{const f=fixture(t);f.write('booklets/mathsmap-sources/Stage 4/Probability.md','# Calculating Probability\n\nAll outcomes must be equally likely.\n'+working+'\n\n### Example\nA bag contains3red and7blue counters. The probability of red is3/10.\n\nFoundation\n\n1. Find the probability of blue.\n');f.write('booklets/mathsmap-sources/Stage 4/Fractions.md','# Dividing Fractions\n\nUse reciprocal notation and fraction language.\n\n### Example\n2/3 divided by1/5=10/3.\n');const r=f.select();assert(r.sources.length);assert(r.sources.every(x=>/Probability/.test(x.path)));assert(r.evidence.some(x=>x.excerpt.includes(working)));assert(r.sources.every(x=>x.support==='indirect'));assert.equal(r.accepted,false);assert(r.normalizedChars<=10000);});
test('only generic fraction or qualitative chance language yields no count-route candidate',t=>{const f=fixture(t);f.write('booklets/mathsmap-sources/Stage 4/Fractions.md','# Fractions\n\n### Example\nFraction notation and language use numerator and denominator.\n');f.write('booklets/mathsmap-sources/Stage 4/Probability.md','# Describing Probability\n\n### Example\nDescribe the chance as likely or unlikely.\n');const r=f.select();assert.deepEqual(r.sources,[]);assert.equal(r.dispatchReady,false);assert(r.gaps.some(x=>x.kind==='no-relevant-source-candidate'&&x.classification==='lexical-selection-miss-not-established-source-gap'));});
test('geometry object/angle naming works without literal geometry and rejects generic variation',t=>{const f=fixture(t,{title:'Use geometrical language and notation',blurb:'Name and label points, lines, intervals, rays and angles by convention.',stage:4});f.write('booklets/mathsmap-sources/Stage 4/Objects.md','# Points Lines Rays\n\nPoint A marks a position. Ray AB starts at A and extends through B. Line AB extends both ways.\n\n### Example\nName Ray BA and Interval AB.\n\n# Labelling Angles\n\nThe middle letter names the vertex. Angle ABC has vertex B.\n\n### Example\nLabel angle CBA with the same vertex.\n');f.write('booklets/mathsmap-sources/Stage 6 Standard/Reciprocal.md','# Notation and Language of Direct Variation\n\n### Example\nUse notation and language for reciprocal relationships.\n');const r=f.select();assert(r.sources.some(x=>x.section==='Points Lines Rays'));assert(r.sources.some(x=>x.section==='Labelling Angles'));assert(r.sources.every(x=>/Objects/.test(x.path)));assert(!r.evidence.some(x=>/variation|reciprocal/i.test(x.excerpt)));});
test('geometry generic-word decoy alone never dispatches unrelated notation',t=>{const f=fixture(t,{title:'Use geometry language and notation',blurb:'Name rays and angles.',stage:4});f.write('booklets/mathsmap-sources/Stage 6 Standard/Reciprocal.md','# Notation and Language of Direct Variation\n\n### Example\nThe notation expresses reciprocal relationships.\n');const r=f.select();assert.deepEqual(r.sources,[]);assert.equal(r.dispatchReady,false);});
test('a geometry mention does not import vector naming into elementary ray notation',t=>{const f=fixture(t,{title:'Use geometry language and notation',blurb:'Name rays, lines and angles.',stage:4});f.write('booklets/mathsmap-sources/Stage 6 Extension 1/Vectors.md','# Point to Point Notation\n\nGeometry uses vector notation. Ray AB describes a vector function.\n\n### Example\nUse vector AB.\n');assert.deepEqual(f.select().sources,[]);});
test('optional taxonomy topic/dotpoint arrays are not required when scope is supplied',t=>{const f=fixture(t);f.write('booklets/mathsmap-sources/Stage 4/Probability.md','# Calculating Probability\n\n'+formula+'\n\n### Example\nFavourable outcomes3, total outcomes10.\n');const context=createSourceSelectionContext(f.root);delete context.taxonomy.topics;delete context.taxonomy.dotpoints;assert(f.select({context}).sources.length);});
test('curated and staged exact references bypass the fresh semantic heuristic',t=>{
 const f=fixture(t),p='booklets/mathsmap-sources/Stage 4/Fractions.md',text='# Fractions\n\n### Example\nUse a reciprocal.\n';f.write(p,text);
 const source={path:p,startLine:1,endLine:5,hash:hashValue(text),locator:'Immutable prior decision',support:'candidate'};
 f.write('.agywork/content-campaign/worked-examples-2026-09/pilot-evidence/test-skill.json',{sources:[source]});
 for(const state of[{scope:{stage:3,topicId:'topic',dotPointId:'dp'}},{scope:{stage:3,topicId:'topic',dotPointId:'dp'},stage:{sourceReview:[source]}}]){
  const r=selectSourceEvidence({root:f.root,skillId:'test-skill',state});assert.equal(r.sources.length,1);
  for(const key of['path','hash','startLine','endLine','locator'])assert.equal(r.sources[0][key],source[key]);
  assert.equal(r.evidence[0].rawExcerptHash,hashValue(text));assert.equal(r.accepted,false);
  assert.equal(r.origin,state.stage?'preserved-staged-source-selection':'curated-pilot-selection');assert.equal(fs.readFileSync(path.join(f.root,p),'utf8'),text);
 }
});
for(const blurb of['','Use geometrical objects.'])test('governing requested objects supply geometry naming context when blurb is '+(blurb||'empty'),t=>{const f=fixture(t,{title:'Use geometry language and notation',blurb,stage:4});f.write('data/dotpoints.json',[{id:'dp',topicId:'topic',text:'Name and label points, lines, intervals, rays and angles.',order:1}]);f.write('booklets/mathsmap-sources/Stage 4/Objects.md','# Points Lines Rays\n\nPoint A marks a position. Ray AB starts at A. Line AB extends both ways.\n\n# Labelling Angles\n\nThe vertex of angle ABC is B.\n');f.write('booklets/mathsmap-sources/Stage 6 Standard/Variation.md','# Notation and Language\n\nUse generic variation notation and language.\n');const r=f.select();assert(r.sources.some(x=>x.section==='Points Lines Rays'));assert(r.sources.some(x=>x.section==='Labelling Angles'));assert(r.sources.every(x=>/Objects/.test(x.path)));});
test('no requested object context remains honest miss even with generic geometry words',t=>{const f=fixture(t,{title:'Use geometry language and notation',blurb:'Use geometrical objects.',stage:4});f.write('booklets/mathsmap-sources/Stage 4/Objects.md','# Points Lines Rays\n\nRay AB starts at A.\n');assert.deepEqual(f.select().sources,[]);});
test('mapped wrong subject still cannot bypass representation guards',t=>{const f=fixture(t),p='booklets/mathsmap-sources/Stage 4/Fractions.md';f.write(p,'# Fraction Notation\n\nUse fraction language and notation when dividing fractions.\n');const r=f.select({state:{scope:{stage:3,topicId:'topic',dotPointId:'dp'},sources:[{path:p,mapping:'historical hint'}]}});assert.deepEqual(r.sources,[]);assert.equal(r.dispatchReady,false);});
test('heading-only and practice-only automatic candidates are not treated as teaching',t=>{const f=fixture(t,{title:'Calculate probabilities by counting multistage outcomes',blurb:'Count outcomes using tables.',stage:5});f.write('booklets/mathsmap-sources/Stage 5 Core/Probability.md','# Complementary Events in Multistage Probability\n\n<!-- no teaching -->\n\n# Listing Outcomes in Multistage Experiments\n\nList all equally likely outcomes using tables; probability is favourable outcomes over total outcomes.\n\n### Example\nList the possible outcomes of two spinners.\n\nFoundation\n\n1. List the outcomes of two coins.\n');const r=f.select();assert(r.sources.some(x=>x.section==='Listing Outcomes in Multistage Experiments'));assert(!r.candidateSections.some(x=>x.title==='Complementary Events in Multistage Probability'));const g=fixture(t,{title:'Add fractions',blurb:'Add fractions.'});g.write('booklets/mathsmap-sources/Stage 4/Fractions.md','# Add Fractions\n\nFoundation\n\n1. Add1/2+1/3.\n');assert.deepEqual(g.select().sources,[]);});
test('real fresh source ranking fixes probability/geometry and skips empty multistage parents',()=>{const root=process.cwd(),context=createSourceSelectionContext(root),select=id=>{const file=path.join(root,'booklets/provenance/content-campaign/worked-examples-2026-09/skills/'+id+'.json'),state=JSON.parse(fs.readFileSync(file));return selectSourceEvidence({root,skillId:id,context,state:{scope:state.scope,sources:state.sources,baseline:state.baseline},evidenceDir:'.agywork/nonexistent-curation'});};const probability=select('probability-as-fraction');assert.equal(probability.sources[0].section,'Calculating Probability');assert.equal(probability.sources[0].startLine,554);assert.equal(probability.sources[0].endLine,636);assert(probability.evidence[0].excerpt.includes('number\\ of\\ favourable\\ outcomes'));assert(probability.sources.every(x=>/Probability 1_/.test(x.path)));const geometry=select('geometry-notation');assert.equal(geometry.sources[0].section,'Points Lines Rays');assert(geometry.candidateSections.some(x=>x.title==='Labelling Angles'));assert(geometry.sources.every(x=>/Angle Relationships/.test(x.path)));const counting=select('multistage-probability-by-counting');assert(counting.sources.some(x=>x.section==='Listing Outcomes in Multistage Experiments'));assert(!counting.sources.some(x=>x.section==='Complementary Events in Multistage Probability'));for(const r of[probability,geometry,counting]){assert(r.normalizedChars<=10000);assert.equal(r.accepted,false);for(const source of r.sources)assert.equal(source.hash,hashValue(fs.readFileSync(path.join(root,source.path))));}});
test('real geometric-growth and series preserve their distinct mathematical subject',()=>{const root=process.cwd(),context=createSourceSelectionContext(root);for(const[id,expected]of[['geometric-growth-decay','Review of Exponential Growth and Decay'],['geometric-series-sum','Partial Sum of a Geometric Series']]){const state=JSON.parse(fs.readFileSync(path.join(root,'booklets/provenance/content-campaign/worked-examples-2026-09/skills/'+id+'.json'))),r=selectSourceEvidence({root,skillId:id,context,state:{scope:state.scope,sources:state.sources},evidenceDir:'.agywork/nonexistent-curation'});assert.equal(r.sources[0].section,expected);assert(r.normalizedChars<=10000);}});


