<script>

  import DiagramDraftEditor from './DiagramDraftEditor.svelte';
  import { reviewTargets, studioProject, editFields, splitTheory, mergeTheory, splitQuestionParts, mergeQuestionParts, mergeQuestionContinuation } from '../lib/booklet-review-model.js';
  import { skills } from '../lib/data.js';
  let { project, blockId, selectedTargetId='', onchange, ondraftchange=()=>{}, tabbed=false, onDiagramEdit=null }=$props();
  let reviewTab=$state('Mapping');
  let selected=$state(''), role=$state('teaches'), atomTitle=$state(''), skillText=$state(''), prereqText=$state(''), rationale=$state(''), archetype=$state(''), flag=$state(''), error=$state('');
  const targets=$derived(reviewTargets(project).filter(t=>t.block.id===blockId));
  const target=$derived(targets.find(t=>t.id===selected) ?? targets[0]);
  const mapping=$derived(project.studio?.atoms?.[target?.id] ?? {});
  let loaded='';
  let diagramDrafts=$state({});
  const diagrams=$derived((()=>{const found=[];const visit=(node,path='')=>{if(!node||typeof node!=='object')return;if(node.format&&['tikz','svg','image'].includes(node.format))found.push({diagram:node,path});for(const [key,value] of Object.entries(node))if(value&&typeof value==='object')Array.isArray(value)?value.forEach((item,index)=>visit(item,path+'/'+key+'/'+index)):visit(value,path+'/'+key);};visit(target?.node);return found;})());
  const assetUrl=src=>src?.startsWith('evidence/')?`/__booklet/full-imports/${encodeURIComponent(project.source?.runId??project.id)}/files/lanes/exact/${src}`:src;
  $effect(()=>{if(selectedTargetId)selected=selectedTargetId;});
  $effect(()=>{if(target && loaded!==target.id+JSON.stringify(mapping)){loaded=target.id+JSON.stringify(mapping);role=mapping.role??'teaches';atomTitle=mapping.title??'';skillText=(mapping.skillIds??[]).join(', ');prereqText=(mapping.prerequisiteIds??[]).join(', ');rationale=mapping.rationale??'';archetype=mapping.archetype??'';}});
  function act(fn){try{error='';onchange(fn());}catch(e){error=e.message;}}
  function saveMapping(){act(()=>{const parse=s=>s.split(',').map(x=>x.trim()).filter(Boolean),ids=parse(skillText),known=new Set(skills.map(s=>s.id));if(ids.some(s=>!known.has(s)))throw new Error('Choose existing public skill IDs; propose new public skills separately.');if(parse(prereqText).some(s=>!known.has(s)&&!Object.hasOwn(project.studio?.atoms??{},s)))throw new Error('Choose an existing teaching atom or public skill prerequisite.');if(!rationale.trim())throw new Error('Add a rationale for this mapping.');return editFields(project,[{targetId:target.id,kind:'mapping',after:{title:atomTitle,role,skillIds:ids,prerequisiteIds:parse(prereqText),archetype,rationale}}]);});}
  function addFlag(){if(!flag.trim())return;act(()=>{const p=studioProject(project);p.studio.flags.push({id:crypto.randomUUID(),targetId:target.id,note:flag,resolved:false,at:new Date().toISOString()});flag='';return p;});}
  function resolveFlag(flagId){act(()=>{const p=studioProject(project);p.studio.flags.find(f=>f.id===flagId).resolved=true;return p;});}
</script>
<section class="review-inspector" class:tabbed>
  {#if tabbed}<nav class="review-tabs" aria-label="Review categories">{#each ['Mapping','Diagrams','Flags'] as tab}<button aria-pressed={reviewTab===tab} onclick={()=>reviewTab=tab}>{tab}{tab==='Flags'?' ('+(project.studio?.flags??[]).filter(f=>!f.resolved).length+')':''}</button>{/each}</nav>{:else}<h3>Review this block</h3>{/if}
  {#if target}
    <label>Block or question part<select value={target.id} onchange={e=>selected=e.currentTarget.value}>{#each targets as t}<option value={t.id}>{t.kind} · {t.node.label??t.node.title??t.id}</option>{/each}</select></label>
    <details open hidden={tabbed&&reviewTab!=='Mapping'}><summary>Atom and mapping</summary>
      <label>Teaching atom<input bind:value={atomTitle} placeholder="What can the student do?" /></label>
      <label>Role<select bind:value={role}><option>teaches</option><option>practises</option><option>assesses</option></select></label>
      <label>Public skill IDs<input bind:value={skillText} list="review-skill-ids" placeholder="Comma-separated IDs" /></label><datalist id="review-skill-ids">{#each skills as s}<option value={s.id}>{s.title}</option>{/each}</datalist>
      <label>Prerequisite atom or skill IDs<input bind:value={prereqText} /></label><label>Archetype<input bind:value={archetype} placeholder="e.g. identify-equal-bases" /></label><label>Rationale<textarea bind:value={rationale} rows="3"></textarea></label>
      <button onclick={saveMapping}>Save mapping</button>
      <div class="actions">{#if target.block.type==='question'}<button onclick={()=>act(()=>splitQuestionParts(project,target.id))}>Split part group</button><button onclick={()=>act(()=>mergeQuestionParts(project,target.id))}>Group with next part</button><button onclick={()=>act(()=>mergeQuestionContinuation(project,blockId))}>Join next question continuation</button>{:else}<button onclick={()=>act(()=>splitTheory(project,blockId))}>Split theory</button><button onclick={()=>act(()=>mergeTheory(project,blockId))}>Merge with next</button>{/if}</div>
      <p class="hint">Question parts keep their shared stem and diagrams. Audit each part separately; a teaching atom does not automatically create a public skill.</p>
    </details>
    <details open={tabbed} hidden={tabbed&&reviewTab!=='Diagrams'}><summary>Diagrams ({diagrams.length})</summary><p class="hint">Use known equations and domains, or known geometric constraints. Keep the source image when a faithful reconstruction is uncertain.</p>{#each diagrams as item (project.id+':'+target.id+':'+item.path+':'+item.diagram.id)}{@const d=item.diagram}<article><strong>{d.alt??d.id}</strong>{#if d.format!=='tikz'&&d.src}<img src={assetUrl(d.src)} alt={d.alt??'Source diagram'} style="max-width:100%"/>{/if}{#if d.mathematicalModel}<details><summary>Constraints and model</summary><pre>{JSON.stringify(d.mathematicalModel,null,2)}</pre></details>{/if}{#if d.overlayOf}<p class="hint">Overlay on {d.overlayOf}</p>{/if}{#if onDiagramEdit}<p class="hint">{d.format.toUpperCase()} · {d.role??'Diagram'} · {d.widthMm??78} mm</p><button onclick={event=>onDiagramEdit({target,item,origin:event.currentTarget})}>Edit diagram: {d.alt??d.id??'Diagram'}</button>{:else}<DiagramDraftEditor diagram={d} initialDraft={diagramDrafts[project.id+':'+target.id+':'+item.path+':'+d.id]} ondraft={draft=>{const key=project.id+':'+target.id+':'+item.path+':'+d.id;diagramDrafts[key]=draft;ondraftchange({key,projectId:project.id,targetId:target.id,diagramId:d.id,path:item.path,draft});}} onsave={draft=>act(()=>editFields(project,[{targetId:target.id,path:item.path+(d.format==='tikz'?'/code':'/src'),after:draft.code},{targetId:target.id,path:item.path+'/widthMm',after:draft.width}]))}/>{/if}</article>{/each}</details>
    <details open hidden={tabbed&&reviewTab!=='Flags'}><summary>Flags</summary><label>Comparison or correction<textarea bind:value={flag} rows="2"></textarea></label><button onclick={addFlag}>Add flag</button>{#each (project.studio?.flags??[]).filter(f=>f.targetId===target.id) as f}<p>{f.resolved?'Resolved: ':''}{f.note} {#if !f.resolved}<button onclick={()=>resolveFlag(f.id)}>Resolve after review</button>{/if}</p>{/each}</details>
  {/if}
  {#if error}<p class="error" role="alert">{error}</p>{/if}
</section>
<style>[hidden]{display:none!important}.review-tabs{display:flex;flex-wrap:wrap;gap:4px}.review-tabs button[aria-pressed=true]{box-shadow:inset 0 -3px #438ccc}.tabbed label,.tabbed .hint,.tabbed pre{font-size:14px}.tabbed button,.tabbed input,.tabbed select,.tabbed summary{min-height:36px}.tabbed input,.tabbed select,.tabbed textarea,.tabbed button{background:var(--panel,#fff);color:inherit;border:1px solid var(--border,#becbd7)}.tabbed pre{overflow-wrap:anywhere}.tabbed summary{display:flex;align-items:center}@media(max-width:600px){.tabbed button,.tabbed input,.tabbed select,.tabbed summary{min-height:44px}}.review-inspector{display:grid;gap:.6rem;min-width:0}.review-inspector h3{margin:0}.review-inspector label{display:grid;gap:.25rem;font-size:.75rem}.review-inspector input,.review-inspector select,.review-inspector textarea{box-sizing:border-box;width:100%;padding:.4rem;border:1px solid #b7c9d6;border-radius:4px;font:inherit}details{padding:.5rem;border:1px solid #dbe3eb;border-radius:5px}summary{cursor:pointer;font-weight:600}details label{margin:.4rem 0}button{margin:.2rem;padding:.3rem .45rem;cursor:pointer}.hint{display:block;font-size:.7rem;color:#52697b}.actions{display:flex;flex-wrap:wrap}pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:.65rem}article{margin:.6rem 0;border-bottom:1px solid #ccd8e3}.error{color:#9c3020}@media(pointer:coarse){button,input,select,summary{min-height:44px}}
</style>
