<script>
  import BookletRichText from './BookletRichText.svelte';
  import Tikz from './Tikz.svelte';
  import { REVIEW_KINDS, reviewTargets, studioProject, approvalCurrent, approveTarget, proposalForFields, addProposal, decideProposal, splitTheoryProposal, mergeTheoryProposal, splitQuestionPartsProposal, mergeQuestionPartsProposal, mergeQuestionContinuationProposal, proposalConflict } from '../lib/booklet-review-model.js';
  import { skills } from '../lib/data.js';
  let { project, blockId, selectedTargetId='', onchange }=$props();
  let selected=$state(''), role=$state('teaches'), atomTitle=$state(''), skillText=$state(''), prereqText=$state(''), rationale=$state(''), archetype=$state(''), instruction=$state(''), flag=$state(''), error=$state(''), busy=$state(false);
  const targets=$derived(reviewTargets(project).filter(t=>t.block.id===blockId));
  const target=$derived(targets.find(t=>t.id===selected) ?? targets[0]);
  const mapping=$derived(project.studio?.atoms?.[target?.id] ?? {});
  let loaded='';
  let diagramDrafts=$state({});
  const diagrams=$derived((()=>{const found=[];const visit=(node,path='')=>{if(!node||typeof node!=='object')return;if(node.format&&['tikz','svg','image'].includes(node.format))found.push({diagram:node,path});for(const [key,value] of Object.entries(node))if(value&&typeof value==='object')Array.isArray(value)?value.forEach((item,index)=>visit(item,path+'/'+key+'/'+index)):visit(value,path+'/'+key);};visit(target?.node);return found;})());
  const assetUrl=src=>src?.startsWith('evidence/')?`/__booklet/full-imports/${encodeURIComponent(project.source?.runId??project.id)}/files/lanes/exact/${src}`:src;
  $effect(()=>{if(selectedTargetId)selected=selectedTargetId;});
  $effect(()=>{if(target && loaded!==target.id+JSON.stringify(mapping)){loaded=target.id+JSON.stringify(mapping);role=mapping.role??'teaches';atomTitle=mapping.title??'';skillText=(mapping.skillIds??[]).join(', ');prereqText=(mapping.prerequisiteIds??[]).join(', ');rationale=mapping.rationale??'';archetype=mapping.archetype??'';}});
  const proposals=$derived((project.studio?.proposals??[]).filter(p=>p.operations.some(op=>op.targetId===target?.id||op.sourceIds?.includes(blockId))));
  function act(fn){try{error='';onchange(fn());}catch(e){error=e.message;}}
  function proposeMapping(){act(()=>{const parse=s=>s.split(',').map(x=>x.trim()).filter(Boolean),ids=parse(skillText),known=new Set(skills.map(s=>s.id));if(ids.some(s=>!known.has(s)))throw new Error('Choose existing public skill IDs; propose new public skills separately.');if(parse(prereqText).some(s=>!known.has(s)&&!Object.hasOwn(project.studio?.atoms??{},s)))throw new Error('Choose an existing teaching atom or public skill prerequisite.');if(!rationale.trim())throw new Error('Add a rationale for this mapping.');return addProposal(project,proposalForFields(project,[{targetId:target.id,kind:'mapping',after:{title:atomTitle,role,skillIds:ids,prerequisiteIds:parse(prereqText),archetype,rationale}}],'Teaching atom mapping'));});}
  async function requestAI(kind){busy=true;error='';try{const response=await fetch(`/__booklet/projects/${encodeURIComponent(project.id)}/propose`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({project,kind,instruction,targetIds:targets.map(t=>t.id)})});const result=await response.json();if(!response.ok)throw new Error(result.error);onchange(addProposal(project,result.proposal));}catch(e){error=e.message;}finally{busy=false;}}
  function addFlag(){if(!flag.trim())return;act(()=>{const p=studioProject(project);p.studio.flags.push({id:crypto.randomUUID(),targetId:target.id,note:flag,resolved:false,at:new Date().toISOString()});flag='';return p;});}
  function resolveFlag(flagId){act(()=>{const p=studioProject(project);p.studio.flags.find(f=>f.id===flagId).resolved=true;return p;});}
</script>
<section class="review-inspector">
  <h3>Review this block</h3>
  {#if target}
    <label>Block or question part<select value={target.id} onchange={e=>selected=e.currentTarget.value}>{#each targets as t}<option value={t.id}>{t.kind} · {t.node.label??t.node.title??t.id}</option>{/each}</select></label>
    <div class="approvals">{#each REVIEW_KINDS as kind}<label><input type="checkbox" checked={approvalCurrent(project,target.id,kind)} onchange={e=>act(()=>approveTarget(project,target.id,kind,e.currentTarget.checked))} /> {kind}</label>{/each}</div>
    <details open><summary>Atom and mapping</summary>
      <label>Teaching atom<input bind:value={atomTitle} placeholder="What can the student do?" /></label>
      <label>Role<select bind:value={role}><option>teaches</option><option>practises</option><option>assesses</option></select></label>
      <label>Public skill IDs<input bind:value={skillText} list="review-skill-ids" placeholder="Comma-separated IDs" /></label><datalist id="review-skill-ids">{#each skills as s}<option value={s.id}>{s.title}</option>{/each}</datalist>
      <label>Prerequisite atom or skill IDs<input bind:value={prereqText} /></label><label>Archetype<input bind:value={archetype} placeholder="e.g. identify-equal-bases" /></label><label>Rationale<textarea bind:value={rationale} rows="3"></textarea></label>
      <button onclick={proposeMapping}>Propose mapping correction</button>
      <div class="actions">{#if target.block.type==='question'}<button onclick={()=>act(()=>addProposal(project,splitQuestionPartsProposal(project,target.id)))}>Propose part-group split</button><button onclick={()=>act(()=>addProposal(project,mergeQuestionPartsProposal(project,target.id)))}>Group with next part</button><button onclick={()=>act(()=>addProposal(project,mergeQuestionContinuationProposal(project,blockId)))}>Join next question continuation</button>{:else}<button onclick={()=>act(()=>addProposal(project,splitTheoryProposal(project,blockId)))}>Propose theory split</button><button onclick={()=>act(()=>addProposal(project,mergeTheoryProposal(project,blockId)))}>Propose merge with next</button>{/if}</div>
      <p class="hint">Question parts keep their shared stem and diagrams. Audit each part separately; a teaching atom does not automatically create a public skill.</p>
    </details>
    <details><summary>AI revisions</summary><label>Requested improvement<textarea bind:value={instruction} rows="3" placeholder="Tighten wording while preserving the procedure"></textarea></label><div class="actions"><button disabled={busy} onclick={()=>requestAI('revise')}>Propose changes</button><button disabled={busy} onclick={()=>requestAI('audit')}>Propose atomisation audit</button></div>{#if busy}<p role="status">Preparing a proposal. Your content remains editable.</p>{/if}</details>
    <details><summary>Diagrams ({diagrams.length})</summary><p class="hint">Use known equations and domains, or known geometric constraints. Keep the source image when a faithful reconstruction is uncertain.</p>{#each diagrams as item}{@const d=item.diagram}<article><strong>{d.alt??d.id}</strong>{#if d.format==='tikz'}<Tikz code={d.code}/>{:else if d.src}<img src={assetUrl(d.src)} alt={d.alt??'Source diagram'} style="max-width:100%"/>{/if}{#if d.mathematicalModel}<pre>{JSON.stringify(d.mathematicalModel,null,2)}</pre>{/if}{#if d.overlayOf}<p class="hint">Overlay on {d.overlayOf}</p>{/if}<label>{d.format==='tikz'?'Proposed TikZ':'Proposed image path'}<textarea rows="5" value={diagramDrafts[d.id]??d.code??d.src} oninput={e=>diagramDrafts[d.id]=e.currentTarget.value}></textarea></label><button onclick={()=>act(()=>addProposal(project,proposalForFields(project,[{targetId:target.id,path:item.path+(d.format==='tikz'?'/code':'/src'),after:diagramDrafts[d.id]??d.code??d.src}],'Diagram repair; verify against source constraints')))}>Propose diagram repair</button></article>{/each}</details>
    <details open><summary>Proposals ({proposals.length})</summary>
      {#each proposals as proposal}<article><strong>{proposal.reason}</strong><small>Based on revision {proposal.baseRevision}</small>
        {#each proposal.operations as op}{@const conflict=proposalConflict(project,op)}<div class="change"><p>{op.reason??op.kind} · {op.status}{op.groupId?' · acceptance unit '+op.groupId:''}</p>{#if conflict}<p class="error">Conflict: {conflict}</p>{/if}
          <details><summary>Before / after</summary><div class="diff"><div><b>Before</b>{#if op.kind==='field'}<BookletRichText text={op.before}/>{:else}<pre>{JSON.stringify(op.before,null,2)}</pre>{/if}</div><div><b>After</b>{#if op.kind==='field'}<BookletRichText text={op.after}/>{:else}<pre>{JSON.stringify(op.after,null,2)}</pre>{/if}</div></div></details>
          {#if op.status==='pending'}<button disabled={Boolean(conflict)} onclick={()=>act(()=>decideProposal(project,proposal.id,[op.id],'accept'))}>Accept{op.groupId?' linked changes':''}</button><button onclick={()=>act(()=>decideProposal(project,proposal.id,[op.id],'reject'))}>Reject</button>{/if}
        </div>{/each}
        {#if proposal.operations.some(op=>op.status==='accepted')}<button onclick={()=>act(()=>decideProposal(project,proposal.id,proposal.operations.filter(op=>op.status==='accepted').map(op=>op.id),'undo'))}>Undo accepted batch</button>{/if}
      </article>{/each}
    </details>
    <details open><summary>Flags</summary><label>Comparison or correction<textarea bind:value={flag} rows="2"></textarea></label><button onclick={addFlag}>Add flag</button>{#each (project.studio?.flags??[]).filter(f=>f.targetId===target.id) as f}<p>{f.resolved?'Resolved: ':''}{f.note} {#if !f.resolved}<button onclick={()=>resolveFlag(f.id)}>Resolve after review</button>{/if}</p>{/each}</details>
  {/if}
  {#if error}<p class="error" role="alert">{error}</p>{/if}
</section>
<style>.review-inspector{display:grid;gap:.6rem;min-width:0}.review-inspector h3{margin:0}.review-inspector label{display:grid;gap:.25rem;font-size:.75rem}.review-inspector input,.review-inspector select,.review-inspector textarea{box-sizing:border-box;width:100%;padding:.4rem;border:1px solid #b7c9d6;border-radius:4px;font:inherit}.approvals{display:grid;grid-template-columns:1fr 1fr;gap:.4rem}.approvals label{display:flex;align-items:center}.approvals input{width:auto}details{padding:.5rem;border:1px solid #dbe3eb;border-radius:5px}summary{cursor:pointer;font-weight:600}details label{margin:.4rem 0}button{margin:.2rem;padding:.3rem .45rem;cursor:pointer}.hint,small{display:block;font-size:.7rem;color:#52697b}.actions{display:flex;flex-wrap:wrap}.diff{display:grid;gap:.5rem}.diff>div:first-child{background:#fff1ed}.diff>div:last-child{background:#eff9f0}.diff>div{padding:.5rem;overflow:auto}pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:.65rem}article{margin:.6rem 0;border-bottom:1px solid #ccd8e3}.error{color:#9c3020}</style>
