<script>
  import {locateDocumentNode} from '../../public/libs/maths-editor/document-operations.mjs';
  import {equationRowSpacing,setEquationRowSpacing} from '../../public/libs/maths-editor/equation-spacing.mjs';
  let {editor,questionLabel='Question',onboundary=()=>{}}=$props();
  let revision=$state(0),draft=null,problem=$state('');
  const c=$derived(editor?.documentController);
  const context=$derived.by(()=>{revision;const at=c&&locateDocumentNode(c.doc,c.selectedId);const ancestors=at?.ancestors??[];const table=[...ancestors,at?.node].find(n=>n?.type==='table');const cellEl=c?.surface.querySelector(`[data-id="${CSS.escape(c.selectedId??'')}"]`)?.closest('td,th');const cell=table?.rows.flat().find(n=>n.id===cellEl?.dataset.id);return {node:at?.node,ancestors,table,cell,row:table?.rows.findIndex(r=>r.includes(cell)),math:c?.mathEditing?.field()};});
  const spacing=$derived(context.math?equationRowSpacing(context.math.getValue('latex')):null);
  const cellPadding=$derived.by(()=>{if(!context.cell)return null;const values=['Top','Right','Bottom','Left'].map(side=>context.cell['padding'+side]??context.table.padding);return values.every(v=>v===values[0])?values[0]:null;});
  const paragraphs=$derived.by(()=>{revision;if(draft?.paragraphIds)return draft.paragraphIds.map(id=>locateDocumentNode(c.doc,id)?.node).filter(Boolean);const range=c?.range;if(range&&!range.collapsed){const nodes=[...c.surface.querySelectorAll('[data-type="paragraph"]')].filter(el=>range.intersectsNode(el)).map(el=>locateDocumentNode(c.doc,el.dataset.id)?.node).filter(Boolean);if(nodes.length)return nodes;}return context.node?.type==='paragraph'?[context.node]:[];});
  const paragraph=$derived(paragraphs[0]);
  function common(property,fallback){const values=paragraphs.map(p=>p[property]??fallback);return values.every(v=>v===values[0])?values[0]:'';}
  $effect(()=>{const host=editor;const update=()=>revision++;for(const name of ['document-selection','document-change','focusin','click','keyup'])host?.addEventListener(name,update);return()=>{cancel();for(const name of ['document-selection','document-change','focusin','click','keyup'])host?.removeEventListener(name,update);};});
  function begin(){if(draft)return;onboundary();draft={doc:structuredClone(c.doc),paragraphIds:paragraphs.map(p=>p.id),math:context.math,latex:context.math?.getValue('latex')};}
  function preview(id,key,value){if(value===''||!Number.isFinite(Number(value)))return;begin();const next=structuredClone(draft.doc),at=locateDocumentNode(next,id);if(!at)return;if(key==='rowHeight')at.node.rowHeights[context.row]=Number(value);else if(key==='paddingAll')for(const side of ['Top','Right','Bottom','Left'])at.node['padding'+side]=Number(value);else if(['lineHeight','spaceBefore','spaceAfter'].includes(key)&&at.node.type==='paragraph')for(const target of draft.paragraphIds)locateDocumentNode(next,target).node[key]=Number(value);else at.node[key]=Number(value);if(context.cell&&['spaceBefore','spaceAfter'].includes(key))locateDocumentNode(next,context.cell.id).node.preserveParagraphSpacing=true;const focus=document.activeElement;c.doc=next;c.render();focus?.focus({preventScroll:true});revision++;}
  function equation(value){if(value===''||!Number.isFinite(Number(value)))return;begin();try{draft.math.setValue(setEquationRowSpacing(draft.latex,Number(value)),{silenceNotifications:true});c.capture();c.mathEditing.refresh();problem='';revision++;}catch(e){problem=e.message;}}
  function commit(){if(!draft)return;draft=null;c.remember();c.emit();onboundary();revision++;}
  function cancel(){if(!draft)return;const old=draft;draft=null;c.doc=old.doc;if(old.math?.isConnected)old.math.setValue(old.latex,{silenceNotifications:true});c.render();revision++;onboundary();}
  function key(event){if(event.key==='Escape'&&draft){event.preventDefault();event.stopPropagation();cancel();}if(event.key==='Enter'){event.preventDefault();commit();}}
  function target(id){commit();c.select(c.surface.querySelector(`[data-id="${CSS.escape(id)}"]`));revision++;}
  function preset(value){preview(paragraph.id,'lineHeight',value);commit();}
  function latex(){[...editor.querySelectorAll('.me-math-tools button'),...document.querySelectorAll('.document-toolbar .me-math-tools button')].find(b=>b.textContent==='Edit LaTeX')?.click();}
  function advanced(node){node.append(c.inspector);const organise=()=>{const root=c.inspector.querySelector('.me-common-properties')??c.inspector;for(const el of [...root.children]){const label=el.firstChild?.textContent??'';if(el.tagName==='LABEL'&&/^(Before \(mm\)|After \(mm\)|Line spacing)/.test(label)){el.hidden=true;continue;}if(/JSON|Shading|Text colour|Border colour/.test(label)&&el.tagName==='LABEL'){const details=document.createElement('details'),summary=document.createElement('summary');summary.textContent=/JSON/.test(label)?'Specialist data':label.trim();el.before(details);details.append(summary,el);}}};organise();editor.addEventListener('document-selection',organise);return {destroy(){editor.removeEventListener('document-selection',organise);if(editor.isConnected)editor.append(c.inspector);}};}
</script>

<div class="selection-spacing" data-equation-control role="group" tabindex="-1" aria-label="Selection spacing">
  <nav class="breadcrumb" aria-label="Selection target"><span>{questionLabel}</span>{#each [...context.ancestors,context.node].filter(n=>n?.id&&n.type!=='document') as node}<span aria-hidden="true">›</span><button onclick={()=>target(node.id)}>{node.type==='paragraph'?'Text':node.type==='table'?'Table':node.type==='cell'?'Cell':node.type}</button>{/each}{#if context.math}<span>› Equation</span>{/if}</nav>
  {#if spacing}
    <h3>Equation spacing</h3>
    {#if spacing.supported}
      <label>Between equation lines <span>additional gap (mm)</span><input aria-label="Between equation lines (mm)" type="number" min="0" max="30" step="0.5" placeholder={spacing.mixed?'Mixed':''} value={spacing.valueMm??''} oninput={e=>equation(e.currentTarget.value)} onkeydown={key} onchange={commit}/></label>
      <div class="presets"><button onclick={()=>{equation(Math.max(0,(spacing.valueMm??0)-.5));commit();}}>Tighter</button><button onclick={()=>{equation((spacing.valueMm??0)+.5);commit();}}>Looser</button></div>
    {:else}<p>This equation has no supported outer row structure. Nested matrices keep their own spacing.</p>{/if}
    <button onclick={latex}>Edit LaTeX</button>
  {/if}
  {#if paragraph}
    <h3>{spacing?'Around the equation':context.cell?'Cell text':'Paragraph'}</h3>
    {#if !spacing}<div class="presets" aria-label="Paragraph spacing presets">{#each [1,1.15,1.5,2] as value}<button aria-pressed={common('lineHeight',1.4)===value} onclick={()=>preset(value)}><span class="preview" style:line-height={value}>━<br/>━</span>{value===1?'Single':value===2?'Double':value}</button>{/each}</div>{/if}
    <div class="fields">{#each (spacing?[['spaceBefore','Space before (mm)',0],['spaceAfter','Space after (mm)',2]]:[['lineHeight','Line spacing',1.4],['spaceBefore','Space before (mm)',0],['spaceAfter','Space after (mm)',2]]) as [property,label,fallback]}<label>{label}<input aria-label={label} type="number" min={property==='lineHeight'?1:0} step={property==='lineHeight'?.05:.5} value={common(property,fallback)} placeholder={common(property,fallback)===''?'Mixed':''} oninput={e=>preview(paragraph.id,property,e.currentTarget.value)} onkeydown={key} onchange={commit}/></label>{/each}</div>
  {/if}
  {#if context.cell}<h3>Cell</h3><div class="fields"><label>Cell padding (mm)<input aria-label="Cell padding (mm)" type="number" min="0" step=".5" value={cellPadding??''} placeholder={cellPadding==null?'Mixed':''} oninput={e=>preview(context.cell.id,'paddingAll',e.currentTarget.value)} onkeydown={key} onchange={commit}/></label><label>Row minimum height (mm)<input aria-label="Row minimum height (mm)" type="number" min="4" max="80" step=".5" value={context.table.rowHeights[context.row]??9} oninput={e=>preview(context.table.id,'rowHeight',e.currentTarget.value)} onkeydown={key} onchange={commit}/></label></div>{/if}
  {#if ['image','inline-image'].includes(context.node?.type)}<h3>Image</h3><div class="fields">{#each (context.node.type==='inline-image'?[['width','Width (mm)',18]]:[['width','Width (mm)',78],['spaceBefore','Space above (mm)',0],['spaceAfter','Space below (mm)',0]]) as [property,label,fallback]}<label>{label}<input aria-label={label} type="number" min="0" step=".5" value={context.node[property]??fallback} oninput={e=>preview(context.node.id,property,e.currentTarget.value)} onkeydown={key} onchange={commit}/></label>{/each}</div>{/if}
  {#if problem}<p role="alert">{problem}</p>{/if}
  <details class="advanced"><summary>Advanced {context.table?'table ':''}properties</summary><div class="me-document-editor studio-native-properties" use:advanced></div></details>
</div>

<style>
  .selection-spacing{font:14px system-ui;color:inherit}.breadcrumb{display:flex;flex-wrap:wrap;align-items:center;gap:3px;color:var(--text-muted,#64748b);font-size:12px}.breadcrumb button{border:0;background:transparent;padding:3px;min-height:24px;text-transform:capitalize}h3{font-size:14px;margin:18px 0 8px}p{font-size:13px;line-height:1.5}.fields{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}label{display:grid;gap:5px;margin:10px 0;font-size:13px}label span{color:var(--text-muted,#64748b);font-size:12px}input{width:100%;min-width:0;box-sizing:border-box}button,input,summary{font:inherit;color:inherit;border:1px solid var(--line,#cbd5e1);border-radius:5px;background:var(--panel,#fff);padding:6px;min-height:32px}button,summary{cursor:pointer}.presets{display:flex;gap:5px}.presets button{flex:1}.presets button[aria-pressed=true]{outline:2px solid #52769a}.preview{display:block;font-size:10px;color:#52769a;margin:3px}.advanced{margin-top:20px}.studio-native-properties{border:0!important;padding:0!important;background:transparent!important;color:inherit!important;font:inherit!important;min-width:0}.studio-native-properties :global(.me-properties){display:block!important;padding:6px 0!important;background:transparent!important;border:0!important;color:inherit!important}.studio-native-properties :global(.me-common-properties){display:grid!important;gap:8px}.studio-native-properties :global(label){display:grid!important;gap:4px;font-size:13px!important;min-width:0;margin:0!important}.studio-native-properties :global(input),.studio-native-properties :global(select){width:100%;min-width:0;box-sizing:border-box;min-height:32px;background:var(--panel,#fff);color:inherit;border:1px solid var(--line,#cbd5e1)}.studio-native-properties :global(button){max-width:100%;white-space:normal}.studio-native-properties :global(details){min-width:0}.studio-native-properties :global(.me-properties-title){display:none}.studio-native-properties :global([hidden]){display:none!important}
</style>
