<script>
  import { defaultRecipe, candidatesFromProject, coverageMatrix, assembleBooklet } from '../lib/booklet-assembly.js';
  import { studioProject, addProposal, decideProposal, proposalConflict } from '../lib/booklet-review-model.js';
  import PracticeQuestionRenderer from './PracticeQuestionRenderer.svelte';
  import { createBookletProject } from '../lib/booklet-project-storage.js';
  import { skills, topics, dotpoints } from '../lib/data.js';
  let {project,onchange,oncreated}=$props();
  let recipe=$state(null),external=$state([]),error=$state(''),busy=$state(false),preview=$state(null),topicId=$state(''),groupId=$state('');
  let loaded='';
  const clone=value=>JSON.parse(JSON.stringify(value));
  $effect(()=>{if(project.id!==loaded){loaded=project.id;recipe=clone(project.studio?.recipe??defaultRecipe(project));preview=null;external=[];}});
  const candidates=$derived([...external,...candidatesFromProject(project)]);
  const coverage=$derived(recipe?coverageMatrix(recipe,candidates):[]);
  const generated=$derived((project.studio?.proposals??[]).filter(p=>p.operations.some(op=>op.kind==='candidate-section')));
  const theoryBlocks=$derived(project.sections.flatMap(s=>s.blocks.filter(b=>b.type!=='question'&&!['heading','page-break','spacer'].includes(b.type)).map(b=>({id:b.id,title:b.title||s.title}))));
  const groups=$derived(dotpoints.filter(d=>!topicId||d.topicId===topicId));
  function saveRecipe(){const p=studioProject(project);p.studio.recipe=clone(recipe);onchange(p);}
  function setScope(){recipe.scopeSkillIds=skills.filter(s=>(s.dotPointIds??[]).includes(groupId)).map(s=>s.id);saveRecipe();}
  async function loadBank(){busy=true;error='';try{const response=await fetch('/__booklet/projects/assembly-bank?skills='+encodeURIComponent([...recipe.scopeSkillIds,...recipe.extensions].join(',')));const data=await response.json();if(!response.ok)throw new Error(data.error);external=data.candidates;}catch(e){error=e.message;}finally{busy=false;}}
  function inspect(){try{error='';preview=assembleBooklet(project,recipe,candidates);saveRecipe();}catch(e){error=e.message;}}
  async function create(){busy=true;try{const result=assembleBooklet(project,recipe,candidates);const saved=await createBookletProject(result.project);oncreated(saved.id);}catch(e){error=e.message;}finally{busy=false;}}
  function exception(row,reason){recipe.exceptions[row.key]={reason,approved:false};preview=null;saveRecipe();}
  function ids(text){return text.split(',').map(s=>s.trim()).filter(Boolean);}
  async function generate(row){busy=true;error='';try{const chunk=recipe.chunks.find(c=>c.id===row.chunkId),response=await fetch(`/__booklet/projects/${encodeURIComponent(project.id)}/propose`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({project,kind:'generate-gap',gap:{archetype:row.archetype,tier:row.tier,skillIds:chunk.skillIds,prerequisiteIds:chunk.prerequisiteIds},count:Math.min(6,Math.max(1,row.required-row.available))})});const data=await response.json();if(!response.ok)throw new Error(data.error);onchange(addProposal(project,data.proposal));}catch(e){error=e.message;}finally{busy=false;}}
  function decide(proposal,op,decision){try{onchange(decideProposal(project,proposal.id,[op.id],decision));error='';}catch(e){error=e.message;}}
</script>
<details class="assembly-panel project-screen"><summary>Assemble teaching sequence</summary>
  {#if recipe}
    <p>Build a draft from reviewed theory and whole questions. The question bank can cover more than the syllabus grouping selected here.</p>
    <div class="scope"><label>NSW topic<select bind:value={topicId}><option value="">Choose topic</option>{#each topics as topic}<option value={topic.id}>{topic.title??topic.name}</option>{/each}</select></label><label>Content grouping<select bind:value={groupId} onchange={setScope}><option value="">Choose grouping</option>{#each groups as group}<option value={group.id}>{group.title??group.text??group.id}</option>{/each}</select></label><label>Explicit extension skill IDs<input value={recipe.extensions.join(', ')} onchange={e=>{recipe.extensions=ids(e.currentTarget.value);saveRecipe();}} /></label><label>Already-taught prerequisite IDs<input value={recipe.assumedPrerequisites.join(', ')} onchange={e=>{recipe.assumedPrerequisites=ids(e.currentTarget.value);saveRecipe();}} /></label></div>
    <div class="counts">{#each Object.keys(recipe.counts) as key}<label>{key} questions<input type="number" min="0" max="100" value={recipe.counts[key]} onchange={e=>{recipe.counts[key]=Number(e.currentTarget.value);preview=null;saveRecipe();}} /></label>{/each}</div>
    <label class="inline"><input type="checkbox" bind:checked={recipe.optionalMastery} onchange={saveRecipe}/> Mark mastery as optional</label>
    <button onclick={()=>{recipe=defaultRecipe(project);saveRecipe();}}>Refresh chunks from reviewed mappings</button>
    {#each recipe.chunks as chunk,index}<fieldset><legend>Chunk {index+1}</legend><label>Title<input bind:value={chunk.title} onchange={saveRecipe}/></label><label>Skill IDs<input value={chunk.skillIds.join(', ')} onchange={e=>{chunk.skillIds=ids(e.currentTarget.value);saveRecipe();}}/></label><label>Teaching atom IDs<input value={(chunk.teachingAtomIds??[]).join(", ")} onchange={e=>{chunk.teachingAtomIds=ids(e.currentTarget.value);saveRecipe();}}/></label><label>Theory block IDs<input value={chunk.blockIds.join(", ")} list="assembly-blocks" onchange={e=>{chunk.blockIds=ids(e.currentTarget.value);saveRecipe();}}/></label><label>Archetypes<input value={chunk.archetypes.join(', ')} onchange={e=>{chunk.archetypes=ids(e.currentTarget.value);saveRecipe();}}/></label><label>Prerequisite IDs<input value={chunk.prerequisiteIds.join(', ')} onchange={e=>{chunk.prerequisiteIds=ids(e.currentTarget.value);saveRecipe();}}/></label><button disabled={index===0} onclick={()=>{[recipe.chunks[index-1],recipe.chunks[index]]=[recipe.chunks[index],recipe.chunks[index-1]];saveRecipe();}}>Move earlier</button><button onclick={()=>{recipe.chunks.splice(index,1);preview=null;saveRecipe();}}>Remove chunk</button></fieldset>{/each}
    <datalist id="assembly-blocks">{#each theoryBlocks as block}<option value={block.id}>{block.title}</option>{/each}</datalist><button onclick={()=>{recipe.chunks.push({id:crypto.randomUUID(),title:"New chunk",blockIds:[],skillIds:[],teachingAtomIds:[],archetypes:[],prerequisiteIds:[]});saveRecipe();}}>Add teaching chunk</button>
    <button disabled={busy} onclick={loadBank}>Load MathsMap questions</button><button onclick={inspect}>Preview sequence and gaps</button>
    <p>{external.length} MathsMap candidates · {candidates.filter(c=>c.origin==='imported'&&c.reviewed).length} reviewed imported questions · {candidates.filter(c=>c.origin==='generated'&&c.reviewed).length} reviewed generated questions</p>
    {#each coverage.filter(row=>row.status==='gap') as row}<button disabled={busy} onclick={()=>generate(row)}>Generate candidates: {row.chunk} / {row.archetype} / {row.tier}</button>{/each}
    {#each generated as proposal}<details><summary>Generated candidates · {proposal.reason}</summary>{#each proposal.operations as op}{@const conflict=proposalConflict(project,op)}<article><PracticeQuestionRenderer question={op.after.blocks[0]} showSpaces={false} showWorkedSolutions={true}/><p>{op.status} · {op.reason}</p>{#if conflict}<p class="gap">Conflict: {conflict}</p>{/if}{#if op.status==='pending'}<button disabled={Boolean(conflict)} onclick={()=>decide(proposal,op,'accept')}>Add to review workspace</button><button onclick={()=>decide(proposal,op,'reject')}>Reject candidate</button>{:else if op.status==='accepted'}<button onclick={()=>decide(proposal,op,'undo')}>Undo candidate addition</button>{/if}</article>{/each}</details>{/each}
    {#if coverage.length}<div class="matrix"><table><thead><tr><th>Chunk / archetype</th><th>Tier</th><th>Available / required</th><th>Coverage</th><th>Exception</th></tr></thead><tbody>{#each coverage as row}<tr><td>{row.chunk}<br/>{row.archetype}</td><td>{row.tier}</td><td>{row.available} / {row.required}</td><td>{row.status}</td><td><input aria-label={`Exception rationale ${row.key}`} placeholder="Why this tier does not apply" value={row.reason} onchange={e=>exception(row,e.currentTarget.value)}/><label class="inline"><input type="checkbox" disabled={!row.reason.trim()} checked={recipe.exceptions[row.key]?.approved??false} onchange={e=>{recipe.exceptions[row.key].approved=e.currentTarget.checked;saveRecipe();}}/>Approve exception</label></td></tr>{/each}</tbody></table></div>{/if}
    {#if preview}<h4>Proposed sequence</h4><ol>{#each preview.project.sections as section}<li>{section.title}{section.optional?' (optional)':''} · {section.blocks.filter(b=>b.type==='question').length} questions</li>{/each}</ol><p>{preview.gaps.length} gaps remain after reserving distinct questions for each section.</p>{#each preview.gaps as gap}<p class="gap">{gap.section} {gap.archetype??''} {gap.tier??''}: {gap.reason??`${gap.selected}/${gap.required} selected`}</p>{/each}<button disabled={busy} onclick={create}>Create independent draft booklet</button>{/if}
  {/if}
  {#if error}<p role="alert" class="gap">{error}</p>{/if}
</details>
<style>.assembly-panel{margin:1rem 0;padding:1rem;border:1px solid #c4d4df;border-radius:8px;background:white}.assembly-panel summary{font-weight:700;cursor:pointer}.scope,.counts{display:flex;flex-wrap:wrap;gap:.8rem}.assembly-panel label{display:grid;gap:.25rem;font-size:.8rem}.assembly-panel input,.assembly-panel select{padding:.4rem;border:1px solid #c0ced8;border-radius:4px;max-width:340px}.counts input{width:65px}fieldset{display:inline-grid;gap:.35rem;vertical-align:top;width:260px;margin:.5rem;border:1px solid #d4e0e8}button{padding:.4rem .7rem;margin:.3rem;cursor:pointer}.inline{display:flex!important;align-items:center;gap:.4rem!important}.matrix{max-height:420px;overflow:auto}table{border-collapse:collapse;width:100%;font-size:.8rem}th,td{border:1px solid #d3dfe7;padding:.45rem;text-align:left}.gap{color:#994020}</style>
