<script>
 import {untrack,getContext} from 'svelte';
 import MathsEditor from './MathsEditor.svelte';
 import DiagramDraftEditor from './DiagramDraftEditor.svelte';
 import BookletArrangement from './BookletArrangement.svelte';
 import BookletRichText from './BookletRichText.svelte';
 import {setGroupAnswerSpaceHeight,resolveArrangement,replaceArrangementContent,findContent,applyArrangementContent,addArrangementText,removeArrangementText} from '../lib/booklet-arrangement.js';
 import {copy,findArrangement,arrangementParent,transformArrangement,arrangementItems} from '../../public/libs/maths-editor/arrangement-model.mjs';
 import {houseStyleVariables} from '../lib/booklet-house-style.js';
 import {validSourceRegion} from '../lib/diagram-source-region.js';
 let {session,onsave,onchange=()=>{}}=$props();
 const getLabels=getContext('booklet-labels');
 let block=$state(untrack(()=>copy(session.block))),tree=$state(untrack(()=>resolveArrangement(session.block,session.arrangement).tree)),history=$state([]),future=$state([]),selected=$state(''),multi=$state([]),error=$state(''),destination=$state(''),showSource=$state(false),editContent=$state(false),contentDraft=$state(null),contentChild=$state(),showSolutions=$state(true);
 const resolved=$derived(resolveArrangement(block,tree,{labels:getLabels?.()}));
 const node=$derived(findArrangement(tree.root,selected)??(resolved.entries.has(selected.slice(7))?{id:selected,type:'item',ref:selected.slice(7)}:null));
 const entry=$derived(node?.ref?resolved.entries.get(node.ref):null);
 const livePreview=$derived.by(()=>{
  if(editContent&&contentDraft&&entry?.kind==='diagram')return applyArrangementContent(block,tree,selected,entry,diagramValue(entry,contentDraft));
  if(editContent&&contentDraft&&entry&&['text','document'].includes(entry.kind))return applyArrangementContent(block,tree,selected,entry,contentDraft.value??contentDraft.document??contentDraft);
  return {block,tree};
 });
 const groupSpaces=$derived(node?.type==='group'?arrangementItems(node).filter(n=>resolved.entries.get(n.ref)?.kind==='space'):[]);
 const groupSpaceHeight=$derived.by(()=>{const heights=groupSpaces.map(n=>n.height??resolved.entries.get(n.ref).value);return heights.length&&heights.every(h=>h===heights[0])?heights[0]:'';});
 const parent=$derived(arrangementParent(tree.root,selected));
 const options=$derived.by(()=>{const out=[];function walk(n,depth=0){const entry=resolved.entries.get(n.ref);out.push({id:n.id,depth,preview:['text','document'].includes(entry?.kind)?entry.value:null,label:entry?.title??n.title??(n.direction==='row'?'Row':'Group')});n.children?.forEach(c=>walk(c,depth+1));}walk(tree.root);return out;});
 selected=untrack(()=>{if(session.selectedArrangementId&&findArrangement(tree.root,session.selectedArrangementId))return session.selectedArrangementId;const entries=[...resolved.entries.values()];const e=entries.find(e=>session.selectedDiagramId&&e.diagramId===session.selectedDiagramId||session.selectedNodeId&&(e.nodeId===session.selectedNodeId||e.value&&typeof e.value==='object'&&findContent(e.value,session.selectedNodeId)))??entries.find(e=>e.ownerId===session.rootId&&e.field===(session.pointer??'').slice(1));return e?(arrangementItems(tree.root).find(n=>n.ref===e.ref)?.id??'layout:'+e.ref):tree.root.id;});
 function snapshot(){return {block:copy(block),tree:copy(tree),selected};}
 function changed(){onchange(getValue());}
 function transact(action){const before=snapshot();try{action();history=[...history,before];future=[];error='';changed();return true;}catch(e){block=before.block;tree=before.tree;selected=before.selected;error=e.message;return false;}}
 function apply(command,options={}){transact(()=>{tree=transformArrangement(tree,command,selected,options);});}
 function select(id){if(editContent&&!flushContent())return;selected=id;multi=[id];editContent=false;}
 function setProperties(patch){if(entry?.kind==='diagram'&&contentDraft&&!flushContent())return;transact(()=>{tree=transformArrangement(tree,'properties',selected,patch);if(patch.width>0&&entry?.kind==='diagram')block=replaceArrangementContent(block,entry,{...entry.value,widthMm:patch.width});if(patch.width>0&&entry?.value?.blocks?.[0]?.type==='table'){const doc=copy(entry.value);doc.blocks[0].widthMm=patch.width;block=replaceArrangementContent(block,entry,doc);}});}
 function preset(){if(node?.type!=='group')return;transact(()=>{const all=arrangementItems(node),graphs=all.filter(i=>resolved.entries.get(i.ref)?.kind==='diagram'),tables=all.filter(i=>resolved.entries.get(i.ref)?.value?.blocks?.[0]?.type==='table');if(!graphs.length||!tables.length)throw Error('Select a group containing a graph and table');const remaining=all.filter(i=>!graphs.includes(i)&&!tables.includes(i)),labels=remaining.filter(i=>resolved.entries.get(i.ref)?.kind==='label'),responses=remaining.filter(i=>!labels.includes(i));const next=copy(tree),target=findArrangement(next.root,selected),id=crypto.randomUUID();target.children=[...labels,{id:id+':row',type:'group',direction:'row',gap:2,children:[{id:id+':left',type:'group',direction:'stack',gap:2,children:[...graphs,...tables]},{id:id+':right',type:'group',direction:'stack',gap:2,children:responses}]}];tree=next;});}
 function move(id,target,position){transact(()=>{tree=transformArrangement(tree,'move',id,{targetId:target,position});});}
 function resize(id,weights){transact(()=>{const next=copy(tree),n=findArrangement(next.root,id);n.children.forEach((c,i)=>c.weight=weights[i]);tree=next;});}
 function restore(value){block=value.block;tree=value.tree;selected=value.selected;editContent=false;contentDraft=null;changed();}
 function undo(){if(editContent)flushContent();if(history.length){future=[...future,snapshot()];const v=history.at(-1);history=history.slice(0,-1);restore(v);}}
 function redo(){if(future.length){history=[...history,snapshot()];const v=future.at(-1);future=future.slice(0,-1);restore(v);}}
 function diagramValue(entry,draft){return {...entry.value,[entry.value.format==='tikz'?'code':'src']:draft.code,widthMm:draft.width,align:draft.align,sourceRegion:draft.sourceRegion,colourMode:draft.colourMode,mathematicalModel:draft.mathematicalModel};}
 function flushContent(){if(!contentDraft)return true;const draft=contentChild?.getValue()??contentDraft;const current=entry;const success=transact(()=>{
   if(current.kind==='diagram'){if(draft.valid===false)throw Error('Correct the graph settings before saving');if(!Number.isFinite(draft.width)||draft.width<5||draft.width>190)throw Error('Diagram width must be between 5 and 190 mm');if(draft.sourceRegion&&!validSourceRegion(draft.sourceRegion))throw Error('Crop must stay within the original image');const applied=applyArrangementContent(block,tree,selected,current,diagramValue(current,draft));block=applied.block;tree=applied.tree;}
   else {const applied=applyArrangementContent(block,tree,selected,current,draft.value??draft.document??draft);block=applied.block;tree=applied.tree;selected=applied.selected;}
  });if(success)contentDraft=null;return success;}
 export function getValue(){return {block:copy(block),arrangement:copy(tree)};}
 export function save(){if(editContent&&!flushContent())return;if(!error)onsave(getValue());}
 const removableText=$derived(entry?.kind==='text'||entry?.kind==='document'&&entry.value.blocks[0]?.type==='paragraph');
 function removeText(){if(transact(()=>{const result=removeArrangementText(block,tree,selected,entry);block=result.block;tree=result.tree;selected=result.selected;})){editContent=false;contentDraft=null;multi=[];}}
 function addText(){if(editContent&&!flushContent())return;editContent=false;contentDraft=null;if(transact(()=>{const result=addArrangementText(block,tree,selected);block=result.block;tree=result.tree;selected=result.selected;})){multi=[selected];editContent=true;}}
 const assetUrl=s=>s?.startsWith('evidence/')?session.assetBase+s:s;
 function internalSpace(property,value){transact(()=>{const doc=copy(entry.value);doc.blocks[0][property]=Math.max(0,Number(value));block=replaceArrangementContent(block,entry,doc);});}
</script>
<div class="question-workspace" style={houseStyleVariables(session.houseStyleVersion)}>
 <div class="arr-toolbar"><button onclick={undo} disabled={!history.length}>Undo edit</button><button onclick={redo} disabled={!future.length}>Redo edit</button><button onclick={addText}>Add text</button><button aria-pressed={showSource} onclick={()=>showSource=!showSource}>Compare source</button><label><input type="checkbox" bind:checked={showSolutions}/> Show solutions</label><span>Question width: {Number(session.widthMm??180).toFixed(1)} mm</span></div>
 {#if error}<p role="alert">{error}</p>{/if}
 <div class="workspace-columns" class:content-open={editContent&&!!entry}>
  <aside aria-label="Question structure">
   <strong>Question structure</strong><p class="hint">Select a group or item. Drag onto a group to move inside, or above/below an item to reorder.</p>
   {#each options as option}<div class="tree-entry" style:padding-left={Math.min(option.depth,4)*8+'px'}><input type="checkbox" aria-label={'Include '+option.label+' in group'} checked={multi.includes(option.id)} onchange={e=>multi=e.currentTarget.checked?[...multi,option.id]:multi.filter(id=>id!==option.id)}/><button class:active={selected===option.id} onclick={()=>select(option.id)}><span>{option.label}</span>{#if option.preview}<div class="tree-preview"><BookletRichText text={option.preview} alignRelations={false}/></div>{/if}</button></div>{/each}
   {#if [...resolved.entries.values()].some(e=>(e.role?.startsWith('answer-')||e.role==='solution-overlay'))}<details><summary>Answers and solutions</summary>{#each [...resolved.entries.values()].filter(e=>(e.role?.startsWith('answer-')||e.role==='solution-overlay')) as e}<button onclick={()=>{select('layout:'+e.ref);editContent=true;}}>{e.ownerId.split('-').at(-1)} · {e.role==='answer-short'?'Short answer':'Worked solution'}</button>{/each}</details>{/if}
  </aside>
  <div class="arr-canvas"><div class="question-paper" style:width={(session.widthMm??180)+'mm'}><BookletArrangement block={livePreview.block} arrangement={livePreview.tree} {selected} onselect={select} onresize={resize} onmeasure={(id,patch)=>{selected=id;setProperties(patch);}} onmove={move} {assetUrl} {showSolutions}/></div>{#if showSource&&session.sourceUrl}<img class="source-page" src={session.sourceUrl} alt="Original source page"/>{/if}</div>
  {#if !editContent||!entry}<aside aria-label="Selection properties">
   {#if node}<strong>{entry?.title??(node.direction==='row'?'Row':'Group')}</strong>
   {#if entry&&['text','document','diagram'].includes(entry.kind)}<button onclick={()=>editContent=true}>Edit selected content</button>{/if}
   {#if node.type==='group'}<label>Group name<input type="text" value={node.title??''} onchange={e=>setProperties({title:e.currentTarget.value})}/></label>{/if}
   <div class="commands"><button disabled={!parent} onclick={()=>apply('before')}>Move before</button><button disabled={!parent} onclick={()=>apply('after')}>Move after</button><button disabled={!parent} onclick={()=>apply('out')}>Move out of column</button><button disabled={!parent} onclick={()=>apply('full-width')}>Full width</button><button disabled={!parent} onclick={()=>apply('group',{ids:multi.length?multi:[selected]})}>Group</button><button disabled={!parent||node.type!=='group'} onclick={()=>apply('ungroup')}>Ungroup</button></div>
   {#if node.type==='group'}<div class="commands"><button aria-pressed={node.direction!=='row'} onclick={()=>setProperties({direction:'stack'})}>Stack</button><button aria-pressed={node.direction==='row'} onclick={()=>setProperties({direction:'row'})}>Side by side</button><button onclick={preset}>Graph and table beside responses</button></div>{/if}
   {#if node.type==='group'&&groupSpaces.length}<label>Answer space height (mm)<input type="number" aria-label="Group answer space height (mm)" min="0" max="180" step=".5" placeholder="Mixed" value={groupSpaceHeight} onchange={e=>{if(e.currentTarget.value!=='')transact(()=>{tree=setGroupAnswerSpaceHeight(tree,resolved.entries,selected,Number(e.currentTarget.value));});}}/></label><p class="hint">Applies to all {groupSpaces.length} answer spaces in this group, including nested groups.</p>{/if}
   <label>Destination<select bind:value={destination}><option value="">Choose group / column</option>{#each options.filter(o=>findArrangement(tree.root,o.id)?.type==='group'&&o.id!==selected) as o}<option value={o.id}>{o.label}</option>{/each}</select></label><button disabled={!destination} onclick={()=>move(selected,destination,'inside')}>Move into column / group</button>
   {#each [['before','Space above (mm)'],['after','Space below (mm)'],['inset','Indent (mm)'],['width','Width (mm)']] as [property,label]}<label>{label}<input type="number" aria-label={label} min="0" max="190" step=".5" value={node[property]??0} onchange={e=>setProperties({[property]:Number(e.currentTarget.value)})}/></label>{/each}
   {#if node.type==='group'}<label>Gap (mm)<input type="number" min="0" max="30" value={node.gap??2} onchange={e=>setProperties({gap:Number(e.currentTarget.value)})}/></label>{/if}
   {#if parent?.direction==='row'}<label>Column proportion<input type="number" min=".1" step=".1" value={node.weight??1} onchange={e=>setProperties({weight:Number(e.currentTarget.value)})}/></label>{/if}
   <label>Alignment<select value={node.align??'left'} onchange={e=>setProperties({align:e.currentTarget.value})}><option>left</option><option>center</option><option>right</option><option>stretch</option></select></label>
   <label><input type="checkbox" checked={node.keepTogether!==false} onchange={e=>setProperties({keepTogether:e.currentTarget.checked})}/> Keep together</label>
   {#if entry&&['document','text'].includes(entry.kind)}<label><input type="checkbox" checked={!!node.keepInline} onchange={e=>setProperties({keepInline:e.currentTarget.checked})}/> Keep equation and answer on one line</label>{/if}
   {#if entry?.kind==='space'}<label>Answer space height (mm)<input type="number" min="0" max="180" value={node.height??entry.value} onchange={e=>setProperties({height:Number(e.currentTarget.value)})}/></label><button onclick={()=>setProperties({height:15})}>Restore answer space</button>{/if}
   <button onclick={()=>setProperties({before:0,after:0,inset:0,gap:0})}>Reset spacing</button>{#if removableText}<button onclick={removeText}>Remove text</button>{/if}{#if entry?.kind==='space'}<button onclick={()=>setProperties({height:0})}>Remove answer space</button>{/if}
   {#if entry?.kind==='document'&&['paragraph','table','spacer'].includes(entry.value.blocks[0]?.type)}
    {@const content=entry.value.blocks[0]}
    {#each content.type==='table'?[['marginBefore','Table space above (mm)'],['marginAfter','Table space below (mm)']]:content.type==='spacer'?[['height','Spacer height (mm)']]:[['spaceBefore','Paragraph space above (mm)'],['spaceAfter','Paragraph space below (mm)'],['indent','Paragraph indent (mm)']] as [property,label]}<label>{label}<input type="number" min="0" step=".5" value={content[property]??0} onchange={e=>internalSpace(property,e.currentTarget.value)}/></label>{/each}
   {/if}
   {/if}
  </aside>{/if}
 {#if editContent&&entry}<section class="selected-content" aria-label="Selected content editor"><header><strong>Edit {entry.title}<small>Text changes preview as you type. Empty text leaves no gap.</small></strong><button onclick={()=>{if(flushContent())editContent=false;}}>Apply to question</button>{#if removableText}<button onclick={removeText}>Remove text</button>{/if}<button onclick={()=>{editContent=false;contentDraft=null;}}>Discard content draft</button></header>
  {#key selected+(entry.kind==='diagram'?':'+entry.value.widthMm:'')}{#if entry.kind==='diagram'}<DiagramDraftEditor bind:this={contentChild} diagram={entry.value} alignment={['left','center','right'].includes(node?.align)?node.align:'left'} colourMode={entry.value.colourMode??session.diagramColourModes?.[entry.diagramId]??'original'} assetBase={session.assetBase} focused={true} ondraft={d=>{contentDraft=d;onchange(getValue());}} onsave={d=>{contentDraft=d;if(flushContent())editContent=false;}}/>{:else}<MathsEditor bind:this={contentChild} value={entry.value} selectedNodeId={entry.value?.blocks?.[0]?.id} inline={true} session={{houseStyleVersion:session.houseStyleVersion,defaultLineHeight:entry.role==='solution'?1.8:undefined}} onchange={d=>{contentDraft=d;onchange(getValue());}}/>{/if}{/key}
 </section>{/if}
 </div>
</div>
<style>
 .tree-entry{min-width:0}.tree-entry button{min-width:0;overflow:hidden}.tree-preview{max-height:48px;overflow:hidden;font-size:12px;pointer-events:none}.tree-preview :global(p){margin:0!important}.tree-preview :global(.document-content){font-size:12px}
 @media(min-width:1001px){.question-workspace .workspace-columns{grid-template-columns:200px minmax(0,1fr) minmax(320px,360px)}.question-workspace .workspace-columns.content-open{grid-template-columns:200px minmax(0,1fr) minmax(440px,.9fr)}}
 .question-workspace{padding:12px}.arr-toolbar{display:flex;gap:12px;align-items:center;flex-wrap:wrap;margin-bottom:12px}.arr-toolbar span{margin-left:auto;font-size:13px}.workspace-columns{display:grid;grid-template-columns:220px minmax(0,1fr) 240px;gap:12px}aside{max-height:65vh;overflow:auto;padding:10px;border:1px solid #ccd5df;border-radius:6px;font-size:13px}aside label{display:flex;justify-content:space-between;align-items:center;gap:5px;margin:8px 0}aside input[type=number]{width:65px}aside select{max-width:155px}.tree-entry{display:flex;align-items:start}.tree-entry button{white-space:pre-wrap;text-align:left;flex:1;border:0;font-size:12px;margin:0}.tree-entry input{margin-top:10px}.active{background:#dceeff!important;color:#183b58!important}.arr-canvas{overflow:auto;background:#e6eaf0;padding:16px;max-height:70vh}.question-paper{box-sizing:content-box;padding:8mm;background:white;color:#24282d;min-height:80mm}.source-page{max-width:100%;margin-top:12px}.commands{display:flex;flex-wrap:wrap;gap:4px;margin:10px 0}.commands button{font-size:12px;padding:5px}.hint{font-size:12px;color:var(--muted,#7890a5);line-height:1.4}button,input,select{font:inherit;min-height:32px;border:1px solid #bbc8d4;border-radius:4px;background:var(--panel,#fff);color:inherit;padding:4px 7px}button{cursor:pointer}button:disabled{opacity:.45}.workspace-columns.content-open{grid-template-columns:170px minmax(0,1fr) minmax(360px,.9fr)}.selected-content{min-width:0;max-height:70vh;overflow:auto;border:2px solid #268cff;padding:12px}.selected-content small{display:block;font-size:12px;font-weight:400;margin-top:4px}.selected-content header{flex-wrap:wrap}.selected-content header{display:flex;gap:10px;align-items:center;margin-bottom:10px}.selected-content header strong{margin-right:auto}[role=alert]{color:#a32d25}@media(max-width:1000px){.workspace-columns.content-open{grid-template-columns:minmax(0,1fr) minmax(320px,1fr)}.content-open>aside:first-child{grid-column:1/-1;max-height:140px}.workspace-columns{grid-template-columns:170px minmax(0,1fr)}.workspace-columns>aside:last-child{grid-column:1/-1;max-height:none}.arr-canvas{max-height:55vh}}
 @media(max-width:650px){.workspace-columns.content-open{grid-template-columns:1fr}.selected-content{max-height:none}}
</style>
