<script>
 import {untrack,getContext} from 'svelte';
 import BookletInspectorTabs from './BookletInspectorTabs.svelte';
 import BookletPageControls from './BookletPageControls.svelte';
 import MathsEditor from './MathsEditor.svelte';
 import DiagramDraftEditor from './DiagramDraftEditor.svelte';
 import BookletArrangement from './BookletArrangement.svelte';
 import BookletRichText from './BookletRichText.svelte';
 import {setGroupAnswerSpaceHeight,resolveArrangement,replaceArrangementContent,findContent,applyArrangementContent,addArrangementText,removeArrangementText} from '../lib/booklet-arrangement.js';
 import {copy,findArrangement,arrangementParent,transformArrangement,arrangementItems} from '../../public/libs/maths-editor/arrangement-model.mjs';
 import {houseStyleVariables} from '../lib/booklet-house-style.js';
 import {validSourceRegion} from '../lib/diagram-source-region.js';
 let {session,onsave,onchange=()=>{}}=$props();
 let showStructure=$state(false);
 let inspectorTab=$state('layout'),expanded=$state(new Set()),pageActions=$state([]);
 const getLabels=getContext('booklet-labels');
 let block=$state(untrack(()=>copy(session.block))),tree=$state(untrack(()=>resolveArrangement(session.block,session.arrangement).tree)),history=$state([]),future=$state([]),selected=$state(''),multi=$state([]),error=$state(''),destination=$state(''),showSource=$state(false),editContent=$state(false),contentDraft=$state(null),contentChild=$state(),showSolutions=$state(true);
 const resolved=$derived(resolveArrangement(block,tree,{labels:getLabels?.()}));
 const node=$derived(findArrangement(tree.root,selected)??(resolved.entries.has(selected.slice(7))?{id:selected,type:'item',ref:selected.slice(7)}:null));
 const entry=$derived(node?.ref?resolved.entries.get(node.ref):null);
 const livePreview=$derived.by(()=>{
  if(editContent&&contentDraft&&entry?.kind==='diagram')return applyArrangementContent(block,tree,selected,entry,diagramValue(entry,contentDraft));
  if(editContent&&contentDraft&&entry&&['text','document'].includes(entry.kind))return applyArrangementContent(block,tree,selected,entry,contentDraft.value??contentDraft.document??contentDraft);
  return {block,tree};
 });
 const groupSpaces=$derived(node?.type==='group'?arrangementItems(node).filter(n=>resolved.entries.get(n.ref)?.kind==='space'):[]);
 const groupSpaceHeight=$derived.by(()=>{const heights=groupSpaces.map(n=>n.height??resolved.entries.get(n.ref).value);return heights.length&&heights.every(h=>h===heights[0])?heights[0]:'';});
 const parent=$derived(arrangementParent(tree.root,selected));
 const options=$derived.by(()=>{const out=[];function walk(n,depth=0,ancestors=[]){const entry=resolved.entries.get(n.ref);out.push({id:n.id,depth,ancestors,group:!!n.children?.length,preview:['text','document'].includes(entry?.kind)?entry.value:null,label:entry?.title??n.title??(n.direction==='row'?'Row':'Group')});n.children?.forEach(c=>walk(c,depth+1,[...ancestors,n.id]));}walk(tree.root);return out;});
 selected=untrack(()=>{if(session.selectedArrangementId&&findArrangement(tree.root,session.selectedArrangementId))return session.selectedArrangementId;const entries=[...resolved.entries.values()];const e=entries.find(e=>session.selectedDiagramId&&e.diagramId===session.selectedDiagramId||session.selectedNodeId&&(e.nodeId===session.selectedNodeId||e.value&&typeof e.value==='object'&&findContent(e.value,session.selectedNodeId)))??entries.find(e=>e.ownerId===session.rootId&&e.field===(session.pointer??'').slice(1));return e?(arrangementItems(tree.root).find(n=>n.ref===e.ref)?.id??'layout:'+e.ref):tree.root.id;});
 $effect(()=>{const id=selected;untrack(()=>{expanded=new Set([...expanded,tree.root.id,...(options.find(o=>o.id===id)?.ancestors??[])]);});});
 const visibleOptions=$derived(options.filter(o=>o.ancestors.every(id=>expanded.has(id))));
 const canPreset=$derived(node?.type==='group'&&arrangementItems(node).some(i=>resolved.entries.get(i.ref)?.kind==='diagram')&&arrangementItems(node).some(i=>resolved.entries.get(i.ref)?.value?.blocks?.[0]?.type==='table'));
 function snapshot(){return {block:copy(block),tree:copy(tree),selected,pageActions:copy(pageActions)};}
 function changed(){onchange(getValue());}
 function transact(action){const before=snapshot();try{action();history=[...history,before];future=[];error='';changed();return true;}catch(e){block=before.block;tree=before.tree;selected=before.selected;error=e.message;return false;}}
 function apply(command,options={}){transact(()=>{tree=transformArrangement(tree,command,selected,options);});}
 function select(id){if(editContent&&!flushContent())return;selected=id;multi=[id];editContent=false;}
 function setProperties(patch){if(entry?.kind==='diagram'&&contentDraft&&!flushContent())return;transact(()=>{tree=transformArrangement(tree,'properties',selected,patch);if(patch.width>0&&entry?.kind==='diagram')block=replaceArrangementContent(block,entry,{...entry.value,widthMm:patch.width});if(patch.width>0&&entry?.value?.blocks?.[0]?.type==='table'){const doc=copy(entry.value);doc.blocks[0].widthMm=patch.width;block=replaceArrangementContent(block,entry,doc);}});}
 function preset(){if(node?.type!=='group')return;transact(()=>{const all=arrangementItems(node),graphs=all.filter(i=>resolved.entries.get(i.ref)?.kind==='diagram'),tables=all.filter(i=>resolved.entries.get(i.ref)?.value?.blocks?.[0]?.type==='table');if(!graphs.length||!tables.length)throw Error('Select a group containing a graph and table');const remaining=all.filter(i=>!graphs.includes(i)&&!tables.includes(i)),labels=remaining.filter(i=>resolved.entries.get(i.ref)?.kind==='label'),responses=remaining.filter(i=>!labels.includes(i));const next=copy(tree),target=findArrangement(next.root,selected),id=crypto.randomUUID();target.children=[...labels,{id:id+':row',type:'group',direction:'row',gap:2,children:[{id:id+':left',type:'group',direction:'stack',gap:2,children:[...graphs,...tables]},{id:id+':right',type:'group',direction:'stack',gap:2,children:responses}]}];tree=next;});}
 function move(id,target,position){transact(()=>{tree=transformArrangement(tree,'move',id,{targetId:target,position});});}
 function resize(id,weights){transact(()=>{const next=copy(tree),n=findArrangement(next.root,id);n.children.forEach((c,i)=>c.weight=weights[i]);tree=next;});}
 function restore(value){block=value.block;tree=value.tree;selected=value.selected;pageActions=value.pageActions??[];editContent=false;contentDraft=null;changed();}
 function undo(){if(editContent)flushContent();if(history.length){future=[...future,snapshot()];const v=history.at(-1);history=history.slice(0,-1);restore(v);}}
 function redo(){if(future.length){history=[...history,snapshot()];const v=future.at(-1);future=future.slice(0,-1);restore(v);}}
 function diagramValue(entry,draft){return {...entry.value,[entry.value.format==='tikz'?'code':'src']:draft.code,widthMm:draft.width,align:draft.align,sourceRegion:draft.sourceRegion,colourMode:draft.colourMode,mathematicalModel:draft.mathematicalModel};}
 function flushContent(){if(!contentDraft)return true;const draft=contentChild?.getValue()??contentDraft;const current=entry;const success=transact(()=>{
   if(current.kind==='diagram'){if(draft.valid===false)throw Error('Correct the graph settings before saving');if(!Number.isFinite(draft.width)||draft.width<5||draft.width>190)throw Error('Diagram width must be between 5 and 190 mm');if(draft.sourceRegion&&!validSourceRegion(draft.sourceRegion))throw Error('Crop must stay within the original image');const applied=applyArrangementContent(block,tree,selected,current,diagramValue(current,draft));block=applied.block;tree=applied.tree;}
   else {const applied=applyArrangementContent(block,tree,selected,current,draft.value??draft.document??draft);block=applied.block;tree=applied.tree;selected=applied.selected;}
  });if(success)contentDraft=null;return success;}
 export function getValue(){return {block:copy(block),arrangement:copy(tree),pageActions:copy(pageActions)};}
 export function save(){if(editContent&&!flushContent())return;if(!error)onsave(getValue());}
 const removableText=$derived(entry?.kind==='text'||entry?.kind==='document'&&entry.value.blocks[0]?.type==='paragraph');
 function removeText(){if(transact(()=>{const result=removeArrangementText(block,tree,selected,entry);block=result.block;tree=result.tree;selected=result.selected;})){editContent=false;contentDraft=null;multi=[];}}
 function addText(){if(editContent&&!flushContent())return;editContent=false;contentDraft=null;if(transact(()=>{const result=addArrangementText(block,tree,selected);block=result.block;tree=result.tree;selected=result.selected;})){multi=[selected];editContent=true;}}
 const assetUrl=s=>s?.startsWith('evidence/')?session.assetBase+s:s;
 function internalSpace(property,value){transact(()=>{const doc=copy(entry.value);doc.blocks[0][property]=Math.max(0,Number(value));block=replaceArrangementContent(block,entry,doc);});}
</script>
<div class="question-workspace" style={houseStyleVariables(session.houseStyleVersion)}>
 <div class="arr-toolbar"><button class="structure-toggle" aria-expanded={showStructure} onclick={()=>showStructure=!showStructure}>Structure</button><button onclick={undo} disabled={!history.length}>Undo edit</button><button onclick={redo} disabled={!future.length}>Redo edit</button><button onclick={addText}>Add text</button><button aria-pressed={showSource} onclick={()=>showSource=!showSource}>Compare source</button><label><input type="checkbox" bind:checked={showSolutions}/> Show solutions</label><span>Question width: {Number(session.widthMm??180).toFixed(1)} mm</span></div>
 {#if error}<p role="alert">{error}</p>{/if}
 <div class="workspace-columns" class:content-open={editContent&&!!entry}>
  <aside class:structure-open={showStructure} aria-label="Question structure">
   <div class="structure-heading"><strong>Structure</strong><details><summary aria-label="Arrangement help">?</summary><p class="hint">Drag onto a group to move inside, or above/below an item to reorder. Select multiple items to group them.</p></details></div>
   {#each visibleOptions as option}<div class="tree-entry" style:padding-left={Math.min(option.depth,4)*8+'px'}>{#if option.group}<button class="tree-toggle" aria-label={'Toggle '+option.label} aria-expanded={expanded.has(option.id)} onclick={()=>{const next=new Set(expanded);if(next.has(option.id))next.delete(option.id);else next.add(option.id);expanded=next;}}>{expanded.has(option.id)?'▾':'▸'}</button>{/if}<input type="checkbox" aria-label={'Include '+option.label+' in group'} checked={multi.includes(option.id)} onchange={e=>multi=e.currentTarget.checked?[...multi,option.id]:multi.filter(id=>id!==option.id)}/><button class:active={selected===option.id} onclick={()=>select(option.id)}><span>{option.label}</span>{#if option.preview}<div class="tree-preview"><BookletRichText text={option.preview} alignRelations={false}/></div>{/if}</button></div>{/each}
   {#if [...resolved.entries.values()].some(e=>(e.role?.startsWith('answer-')||e.role==='solution-overlay'))}<details><summary>Answers and solutions</summary>{#each [...resolved.entries.values()].filter(e=>(e.role?.startsWith('answer-')||e.role==='solution-overlay')) as e}<button onclick={()=>{select('layout:'+e.ref);editContent=true;}}>{e.ownerId.split('-').at(-1)} · {e.role==='answer-short'?'Short answer':'Worked solution'}</button>{/each}</details>{/if}
  </aside>
  <div class="arr-canvas"><div class="question-paper" style:width={(session.widthMm??180)+'mm'}><BookletArrangement block={livePreview.block} arrangement={livePreview.tree} {selected} onselect={select} onresize={resize} onmeasure={(id,patch)=>{selected=id;setProperties(patch);}} onmove={move} {assetUrl} {showSolutions}/></div>{#if showSource&&session.sourceUrl}<img class="source-page" src={session.sourceUrl} alt="Original source page"/>{/if}</div>
  {#if !editContent||!entry}<aside class="arr-properties" aria-label="Selection properties">
   <strong class="selection-breadcrumb">{entry?.title??node?.title??(node?.direction==='row'?'Row':'Group')}</strong>
   <BookletInspectorTabs value={inspectorTab} onchange={value=>inspectorTab=value} id="arrangement-inspector"/>
   <div id="arrangement-inspector-content" role="tabpanel" aria-labelledby={'arrangement-inspector-'+inspectorTab}>
   {#if inspectorTab==='page'}
    {#if session.pageControls}<BookletPageControls {block} onboundary={action=>transact(()=>{pageActions=[...pageActions,action];})} onlayout={patch=>transact(()=>{block={...block,flow:{...block.flow,...patch}};})}/>{#if pageActions.length}<p class="hint">Page changes apply when you save.</p>{/if}{:else}<p class="hint">Page boundaries are managed in the booklet.</p>{/if}
    {#if node}<label class="check"><input type="checkbox" checked={node.keepTogether!==false} onchange={e=>setProperties({keepTogether:e.currentTarget.checked})}/>Keep selected group together</label>{/if}
   {:else if node}
    {#if inspectorTab==='arrange'}
     {#if node.type==='group'}<label>Group name<input value={node.title??''} onchange={e=>setProperties({title:e.currentTarget.value})}/></label><div class="commands"><button aria-pressed={node.direction!=='row'} onclick={()=>setProperties({direction:'stack'})}>Stack</button><button aria-pressed={node.direction==='row'} onclick={()=>setProperties({direction:'row'})}>Side by side</button>{#if canPreset}<button onclick={preset}>Graph and table beside responses</button>{/if}</div>{/if}
     <div class="commands"><button disabled={!parent} onclick={()=>apply('before')}>Move before</button><button disabled={!parent} onclick={()=>apply('after')}>Move after</button><button disabled={!parent} onclick={()=>apply('out')}>Move out of column</button><button disabled={!parent} onclick={()=>apply('full-width')}>Full width</button><button disabled={!parent} onclick={()=>apply('group',{ids:multi.length?multi:[selected]})}>Group</button><button disabled={!parent||node.type!=='group'} onclick={()=>apply('ungroup')}>Ungroup</button></div>
     <label>Destination<select bind:value={destination}><option value="">Choose group / column</option>{#each options.filter(o=>findArrangement(tree.root,o.id)?.type==='group'&&o.id!==selected&&!o.ancestors.includes(selected)) as o}<option value={o.id}>{o.label}</option>{/each}</select></label><button disabled={!destination} onclick={()=>move(selected,destination,'inside')}>Move into column / group</button>
     {#if removableText}<button onclick={removeText}>Remove text</button>{/if}
    {:else}
     <small class="units">Size and spacing (mm)</small><div class="property-grid">
      {#each [['before','Above'],['after','Below'],['inset','Indent'],['width','Width']] as [property,label]}<label>{label}<input type="number" aria-label={property==='before'&&entry?.kind==='diagram'?'Space above image (mm)':({'before':'Space above (mm)','after':'Space below (mm)','inset':'Indent (mm)','width':'Width (mm)'})[property]} min="0" max="190" step=".5" placeholder={property==='width'?'Auto':'0'} value={property==='width'?(node[property]||''):node[property]??0} onchange={e=>setProperties({[property]:Number(e.currentTarget.value)})}/></label>{/each}
      {#if node.type==='group'}<label>Gap<input aria-label="Gap (mm)" type="number" min="0" max="30" value={node.gap??2} onchange={e=>setProperties({gap:Number(e.currentTarget.value)})}/></label>{/if}
      <label title="Zero minimum height fits the content. A larger minimum height keeps space even when Gap is zero. Answer space height controls separate writing areas.">Minimum height<input type="number" aria-label="Minimum height (mm)" min="0" max="180" step=".5" value={node.minHeight??0} onchange={e=>setProperties({minHeight:Number(e.currentTarget.value)})}/></label>
   {#if parent?.direction==='row'}<label>Column proportion<input aria-label="Column proportion" type="number" min=".1" step=".1" value={node.weight??1} onchange={e=>setProperties({weight:Number(e.currentTarget.value)})}/></label>{/if}
      <label>Alignment<select aria-label="Alignment" value={node.align??'left'} onchange={e=>setProperties({align:e.currentTarget.value})}><option value="left">Left</option><option value="center">Centre</option><option value="right">Right</option><option value="stretch">Stretch</option></select></label>
      <label>Vertical alignment<select aria-label="Vertical alignment" value={node.verticalAlign??'top'} onchange={e=>setProperties({verticalAlign:e.currentTarget.value})}><option value="top">Top</option><option value="middle">Middle</option><option value="bottom">Bottom</option></select></label>
      {#if node.type==='group'&&groupSpaces.length}<label title={'Applies to '+groupSpaces.length+' nested answer spaces'}>Answer height<input type="number" aria-label="Group answer space height (mm)" min="0" max="180" step=".5" placeholder="Mixed" value={groupSpaceHeight} onchange={e=>{if(e.currentTarget.value!=='')transact(()=>{tree=setGroupAnswerSpaceHeight(tree,resolved.entries,selected,Number(e.currentTarget.value));});}}/></label>{/if}
      {#if entry?.kind==='space'}<label>Answer height (mm)<input type="number" min="0" max="180" value={node.height??entry.value} onchange={e=>setProperties({height:Number(e.currentTarget.value)})}/></label>{/if}
     </div>
     {#if entry&&['document','text'].includes(entry.kind)}<label class="check"><input type="checkbox" checked={!!node.keepInline} onchange={e=>setProperties({keepInline:e.currentTarget.checked})}/>Keep equation and answer on one line</label>{/if}
     {#if entry?.kind==='document'&&['paragraph','table','spacer'].includes(entry.value.blocks[0]?.type)}
      {@const content=entry.value.blocks[0]}<details class="internal-spacing"><summary>Inside {content.type}</summary><div class="property-grid">{#each content.type==='table'?[['marginBefore','Above'],['marginAfter','Below']]:content.type==='spacer'?[['height','Height']]:[['spaceBefore','Above'],['spaceAfter','Below'],['indent','Indent']] as [property,label]}<label>{label} (mm)<input type="number" min="0" step=".5" value={content[property]??0} onchange={e=>internalSpace(property,e.currentTarget.value)}/></label>{/each}</div></details>
     {/if}
     <div class="commands"><button onclick={()=>setProperties({before:0,after:0,inset:0,gap:0})}>Reset spacing</button>{#if entry?.kind==='space'}<button onclick={()=>setProperties({height:15})}>Restore answer space</button><button onclick={()=>setProperties({height:0})}>Remove answer space</button>{/if}</div>
    {/if}
    {#if entry&&['text','document','diagram'].includes(entry.kind)}<button class="edit-content-button" onclick={()=>editContent=true}>Edit selected content</button>{/if}
   {/if}
   </div>
  </aside>{/if}
 {#if editContent&&entry}<section class="selected-content" aria-label="Selected content editor"><header><strong>Edit {entry.title}<small>Text changes preview as you type. Empty text leaves no gap.</small></strong><button onclick={()=>{if(flushContent())editContent=false;}}>Apply to question</button>{#if removableText}<button onclick={removeText}>Remove text</button>{/if}<button onclick={()=>{editContent=false;contentDraft=null;}}>Discard content draft</button></header>
  {#key selected+(entry.kind==='diagram'?':'+entry.value.widthMm:'')}{#if entry.kind==='diagram'}<DiagramDraftEditor bind:this={contentChild} diagram={entry.value} alignment={['left','center','right'].includes(node?.align)?node.align:'left'} colourMode={entry.value.colourMode??session.diagramColourModes?.[entry.diagramId]??'original'} assetBase={session.assetBase} focused={true} ondraft={d=>{contentDraft=d;onchange(getValue());}} onsave={d=>{contentDraft=d;if(flushContent())editContent=false;}}/>{:else}<MathsEditor bind:this={contentChild} value={entry.value} selectedNodeId={entry.value?.blocks?.[0]?.id} inline={true} session={{houseStyleVersion:session.houseStyleVersion,defaultLineHeight:entry.role==='solution'?1.8:undefined}} onchange={d=>{contentDraft=d;onchange(getValue());}}/>{/if}{/key}
 </section>{/if}
 </div>
</div>
<style>
 .tree-entry{min-width:0}.tree-entry button{min-width:0;overflow:hidden}.tree-preview{max-height:48px;overflow:hidden;font-size:12px;pointer-events:none}.tree-preview :global(p){margin:0!important}.tree-preview :global(.document-content){font-size:12px}
 @media(min-width:1001px){.question-workspace .workspace-columns{grid-template-columns:200px minmax(0,1fr) minmax(320px,360px)}.question-workspace .workspace-columns.content-open{grid-template-columns:200px minmax(0,1fr) minmax(440px,.9fr)}}
 .question-workspace{padding:12px}.arr-toolbar{display:flex;gap:12px;align-items:center;flex-wrap:wrap;margin-bottom:12px}.arr-toolbar span{margin-left:auto;font-size:13px}.workspace-columns{display:grid;grid-template-columns:220px minmax(0,1fr) 240px;gap:12px}aside{overflow:auto;padding:10px;border:1px solid #ccd5df;border-radius:6px;font-size:13px}aside label{display:flex;justify-content:space-between;align-items:center;gap:5px;margin:8px 0}aside input[type=number]{width:65px}aside select{max-width:155px}.tree-entry{display:flex;align-items:start}.tree-entry button{white-space:pre-wrap;text-align:left;flex:1;border:0;font-size:12px;margin:0}.tree-entry input{margin-top:10px}.active{background:#dceeff!important;color:#183b58!important}.arr-canvas{overflow:auto;background:#e6eaf0;padding:16px;max-height:none}.question-paper{box-sizing:content-box;padding:8mm;background:white;color:#24282d;min-height:0}.source-page{max-width:100%;margin-top:12px}.commands{display:flex;flex-wrap:wrap;gap:4px;margin:10px 0}.commands button{font-size:12px;padding:5px}.hint{font-size:12px;color:var(--muted,#7890a5);line-height:1.4}button,input,select{font:inherit;min-height:32px;border:1px solid #bbc8d4;border-radius:4px;background:var(--panel,#fff);color:inherit;padding:4px 7px}button{cursor:pointer}button:disabled{opacity:.45}.workspace-columns.content-open{grid-template-columns:170px minmax(0,1fr) minmax(360px,.9fr)}.selected-content{min-width:0;overflow:auto;border:2px solid #268cff;padding:12px}.selected-content small{display:block;font-size:12px;font-weight:400;margin-top:4px}.selected-content header{flex-wrap:wrap}.selected-content header{display:flex;gap:10px;align-items:center;margin-bottom:10px}.selected-content header strong{margin-right:auto}[role=alert]{color:#a32d25}@media(max-width:1000px){.workspace-columns.content-open{grid-template-columns:minmax(0,1fr) minmax(320px,1fr)}.content-open>aside:first-child{grid-column:1/-1;max-height:140px}.workspace-columns{grid-template-columns:170px minmax(0,1fr)}.workspace-columns>aside:last-child{grid-column:1/-1;max-height:none}.arr-canvas{max-height:none}}
 @media(max-width:650px){.workspace-columns.content-open{grid-template-columns:1fr}.selected-content{max-height:none}}

 .question-workspace{height:100%;box-sizing:border-box;display:flex;flex-direction:column;min-height:0;padding:10px}.workspace-columns{flex:1;min-height:0;grid-template-rows:minmax(0,1fr)}.workspace-columns>aside,.arr-canvas,.selected-content{min-height:0;box-sizing:border-box}.workspace-columns>aside{font-size:14px}.arr-canvas{height:100%;padding:16px}.arr-toolbar{gap:8px;flex:none;margin-bottom:8px;font-size:14px}.arr-properties .selection-breadcrumb{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font-size:13px}.property-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:5px 12px}.arr-properties .property-grid label{display:grid;gap:4px;margin:3px 0;font-size:14px}.arr-properties .property-grid input,.arr-properties .property-grid select{width:100%;max-width:100%;font-size:14px;min-height:32px}.arr-properties .check{justify-content:flex-start;font-size:13px}.arr-properties .check input{min-height:0}.commands button{font-size:14px;min-height:32px}.edit-content-button{margin-top:10px;width:100%}.internal-spacing{position:relative;margin:8px 0}.internal-spacing>div{position:absolute;z-index:10;right:0;top:100%;width:280px;background:var(--panel,#fff);padding:12px;border:1px solid #ccd5df;box-shadow:0 5px 18px #0002}.tree-entry .tree-toggle{flex:0 0 20px;padding:0;min-width:20px}.tree-entry button{font-size:14px}.tree-entry input{width:12px;min-height:0}.tree-preview{font-size:12px;max-height:34px}.structure-heading{display:flex;align-items:center;justify-content:space-between;margin-bottom:8px}.structure-heading details{position:relative}.structure-heading details p{position:absolute;left:0;top:100%;width:220px;padding:12px;background:white;z-index:20;box-shadow:0 4px 16px #0002}.structure-heading summary{cursor:pointer;padding:4px 8px}.arr-properties>strong{margin-bottom:0}
 @media(min-width:1001px){.question-workspace .workspace-columns{grid-template-columns:210px minmax(0,1fr) 320px}.question-workspace .workspace-columns.content-open{grid-template-columns:210px minmax(0,1fr) minmax(380px,.75fr)}}
 @media(max-width:1000px){.question-workspace .workspace-columns,.question-workspace .workspace-columns.content-open{grid-template-columns:minmax(0,1fr) 300px;position:relative}.workspace-columns>aside:first-child{display:none}.workspace-columns>aside:last-child{grid-column:auto}.content-open>aside:first-child{grid-column:auto}.arr-toolbar{flex-wrap:wrap}}
 @media(max-width:650px){.question-workspace .workspace-columns,.question-workspace .workspace-columns.content-open{grid-template-columns:1fr;overflow:auto;grid-template-rows:minmax(260px,1fr) auto}.arr-canvas{height:auto}.arr-properties,.selected-content{overflow:visible}}
 .arr-properties .property-grid input[type=number]{width:100%;max-width:100%}.structure-toggle{display:none}@media(max-width:1000px){.structure-toggle{display:inline-block}.workspace-columns>aside.structure-open{display:block;position:absolute;inset:0 auto 0 0;width:240px;max-height:none;z-index:20;background:var(--panel,#fff);box-shadow:5px 0 18px #0003}}
 .units{display:block;font-size:12px;color:var(--text-muted,#647181);margin:5px 0}</style>
