import test,{after} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {fileURLToPath} from 'node:url';
import {readSinglePageContextPolicy,validateSinglePageContextPolicy} from '../../scripts/booklet/single-page-context-policy.mjs';
const HERE=path.dirname(fileURLToPath(import.meta.url)),F=path.join(HERE,'policy-fixture-'+process.pid);fs.mkdirSync(F);const hash=f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex'),pin=f=>({path:path.resolve(f),hash:hash(f)}),write=(n,x)=>{const f=path.join(F,n);fs.writeFileSync(f,typeof x==='string'?x:JSON.stringify(x));return pin(f);};
const authorization=write('authorization.json',{}),project=write('project.json',{}),saveReceipt=write('save.json',{}),adapter=write('adapter.mjs','// synthetic fixture; never called');
const base={kind:'root-single-page-context-delivery-policy',version:1,status:'approved',authorRole:'root',reviewer:'root synthetic fixture',approvedAt:'2026-09-28T00:00:00.000Z',reason:'Synthetic fixture only; no actual authorization',contextDeliveryOnly:true,actualVisualInspection:false,visualAcceptance:null,maxRenderedPages:1,normalLimit:24000,maxCharacters:64000,runDir:F,reviewRoot:path.join(F,'review'),editions:['student','short','worked'],settlementKey:'1'.repeat(64),renderer:'fixture-renderer',projectReviewHash:'2'.repeat(64),authorization,project,saveReceipt,implementations:[pin(fileURLToPath(new URL('../../scripts/booklet/single-page-context-policy.mjs',import.meta.url))),adapter]};
const actual={authorization,project,saveReceipt,runDir:F,settlementKey:base.settlementKey,renderer:base.renderer,projectReviewHash:base.projectReviewHash,normalLimit:24000,edition:'student',page:70,renderedPageCount:1,renderKeys:['render:70'],renderedKey:'render:70',characters:59979,adapterFile:adapter.path};let seq=0;const policy=p=>write('policy-'+(++seq)+'.json',p);
test('explicit current single-page policy yields case-specific automatic reason and zero inspection claim',()=>{const p=policy(base),r=validateSinglePageContextPolicy(p,actual);assert.match(r.reason,/Automatically issued/);assert.match(r.reason,/59979/);assert.match(r.reason,/no manual inspection or visual acceptance/);assert.equal(r.policy.actualVisualInspection,false);assert.equal(r.policy.visualAcceptance,null);assert.deepEqual(r.policyArtifact,p);validateSinglePageContextPolicy(p,{...actual,characters:64000});});
test('size, multipage, edition, source context and native candidate mismatches reject',()=>{const p=policy(base);for(const change of [{characters:64001},{characters:24000},{renderedPageCount:2},{renderKeys:['render:70','render:71']},{renderedKey:'other'},{edition:'with-short'},{settlementKey:'3'.repeat(64)},{renderer:'changed'},{projectReviewHash:'4'.repeat(64)},{normalLimit:25000},{project:{...project,hash:'5'.repeat(64)}},{page:0},{runDir:path.dirname(F)}])assert.throws(()=>validateSinglePageContextPolicy(p,{...actual,...change}),JSON.stringify(change));});
test('unapproved, enlarged or unpinned policies reject',()=>{for(const change of [{status:'DRAFT'},{maxCharacters:64001},{maxRenderedPages:2},{actualVisualInspection:true},{visualAcceptance:true},{projectReviewHash:null},{reviewRoot:path.dirname(F)},{implementations:[]},{implementations:undefined}])assert.throws(()=>readSinglePageContextPolicy(policy({...base,...change})),JSON.stringify(change));const p=policy({...base,implementations:[adapter,authorization]});assert.throws(()=>validateSinglePageContextPolicy(p,actual),/actual issuer/);});
test('changed approved bytes and changed implementation bytes reject',()=>{const p=policy(base);fs.appendFileSync(p.path,' ');assert.throws(()=>readSinglePageContextPolicy(p),/changed/);const p2=policy(base);fs.appendFileSync(adapter.path,' changed');assert.throws(()=>validateSinglePageContextPolicy(p2,actual),/changed/);});

after(()=>{assert.equal(path.dirname(F),HERE);fs.rmSync(F,{recursive:true,force:true});});
