import fs from 'node:fs';
import path from 'node:path';
import {materializeReconstruction,validateEditableProject} from '../../src/lib/editable-booklet-model.js';
import {saveBookletProject} from './project-studio-server.mjs';
const out=path.resolve(process.argv[2]??'output/linear-pilot'),file=path.join(out,'project.json'),pilot=JSON.parse(fs.readFileSync(path.join(out,'pilot.json'))),previous=fs.existsSync(file)?JSON.parse(fs.readFileSync(file)):null;
let project=materializeReconstruction(pilot,{}, {projectId:'linear-relationships-pilot-v1'});
project.sections.forEach(s=>{const old=previous?.sections.find(p=>p.sourcePageNumber===s.sourcePageNumber);if(old)s.id=old.id;});
project.settings.preserveSourcePages=true;project.source={type:'reconstruction-benchmark-pilot',runId:'linear-relationships-studio-v1',benchmark:'linear-three-model-v1',reviewedSourcePages:pilot.pages.map(p=>p.pageNumber),provenance:'output/linear-pilot/corrections.json'};project.status='draft';
const checked=validateEditableProject(project);if(!checked.valid)throw new Error(checked.errors.join('; '));
if(process.argv.includes('--save'))project=await saveBookletProject(project,{create:true});
fs.writeFileSync(file,JSON.stringify(project,null,2));console.log(JSON.stringify({id:project.id,sections:project.sections.length,status:project.status,saved:process.argv.includes('--save')}));
